using System;
using System.Text;
using System.Text.Json;
using Xunit;
using Flagship.Burner;

namespace Flagship.Burner.Tests;

/// <summary>
/// Golden-vector tests — direct port of apps/burner-mac RecipeTests.swift.
/// The recipes below were produced by the real @flagship/protocol
/// signInstallBlob (IRK seed 7, expiry 2099). If the C# canonical-byte layout
/// or the pure-C# Ed25519 verify drifts from the TypeScript, Load() stops
/// accepting them — that's the regression alarm, and it simultaneously proves
/// the recipe a box receives would sign-verify on that box.
/// </summary>
public class RecipeTests
{
    // Generated by packages/protocol signInstallBlob — do not hand-edit.
    private const string GoldenJson = """
    {
      "version": 2,
      "serverDomain": "home.golden.flagship.services",
      "username": "golden",
      "serverName": "home",
      "phoneDelegatedPubKey": "1398f62c6d1a457c51ba6a4b5f3dbd2f69fca93216218dc8997e416bd17d93ca",
      "registrationUrl": "https://flagshipserver.com/api/server/register",
      "authCode": {
        "version": 1,
        "serial": "01GOLDENTEST",
        "username": "golden",
        "serverName": "home",
        "serverDomain": "home.golden.flagship.services",
        "delegatedPubKey": "1398f62c6d1a457c51ba6a4b5f3dbd2f69fca93216218dc8997e416bd17d93ca",
        "userPubKey": "ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c",
        "issuedAt": 4070908800000,
        "expiresAt": 4102444800000
      },
      "authCodeUserSignature": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "installerGitRef": "main",
      "rckPubKey": "fd1724385aa0c75b64fb78cd602fa1d991fdebf76b13c58ed702eac835e9f618",
      "blobSignatureHex": "cf239ce92c72081578f5f3c781cf6de127472485eee3ce2b7a748f8057d122bce3690ceed82737892f2f5bf9c45d39ee7c50ed36b46a2b52ef58b9c4b3823505"
    }
    """;

    // Generated by signInstallBlob WITH bootUnlockMode:"approve". Proves the C#
    // canonical-byte layout APPENDS bootUnlockMode exactly as @flagship/protocol
    // does — drop the field and this real signature stops verifying.
    private const string ApproveGoldenJson =
        "{\"version\":2,\"serverDomain\":\"home.demoalice.flagship.services\",\"username\":\"demoalice\",\"serverName\":\"home\",\"phoneDelegatedPubKey\":\"1398f62c6d1a457c51ba6a4b5f3dbd2f69fca93216218dc8997e416bd17d93ca\",\"registrationUrl\":\"https://flagshipserver.com/api/server/register\",\"authCode\":{\"version\":1,\"serial\":\"01TESTAPPROV\",\"username\":\"demoalice\",\"serverName\":\"home\",\"serverDomain\":\"home.demoalice.flagship.services\",\"delegatedPubKey\":\"1398f62c6d1a457c51ba6a4b5f3dbd2f69fca93216218dc8997e416bd17d93ca\",\"userPubKey\":\"ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c\",\"issuedAt\":1000,\"expiresAt\":99999999999999},\"authCodeUserSignature\":\"d696674534e72422b93ae38f52d4ebb6777ccf4c562ed0e346bf059dced2585eb41409cb14dcc6ab3b56442d5af1cbbc1d4fcf060f5fde91b33d8d7b470e9f06\",\"installerGitRef\":\"main\",\"rckPubKey\":\"fd1724385aa0c75b64fb78cd602fa1d991fdebf76b13c58ed702eac835e9f618\",\"blobSignatureHex\":\"f29ad6f68c8f72c99f25b158373689724a9bc67ea8a38abd1dc97f81f5d843a9d948885b23facd65ccf99cc6edc4b7bb814f5085a796fce66251bfad583ce500\",\"bootUnlockMode\":\"approve\"}";

    // A recipe carrying diskEncryption:"none" (the Wi-Fi-only fallback),
    // signed by @flagship/protocol signInstallBlob over the trailing `de=none`.
    // Generated by packages/protocol with fixed seeds (userPubKey 8146…9a3e) —
    // the same golden apps/burner-mac RecipeTests.swift pins. If the C#
    // CanonicalBytes dropped or mis-spelled the `de=` append, this valid
    // recipe would be rejected. Do not hand-edit.
    private const string DiskEncryptionNoneGoldenJson =
        "{\"version\":2,\"serverDomain\":\"home.denone.flagship.services\",\"username\":\"denone\",\"serverName\":\"home\",\"phoneDelegatedPubKey\":\"c86d01ad8b2fb694b22ff60e3c9d9e7ed90db5604772b74450d40913b9a9cbaf\",\"registrationUrl\":\"https://flagshipserver.com/api/server/register\",\"authCode\":{\"version\":1,\"serial\":\"01DENONE0001\",\"username\":\"denone\",\"serverName\":\"home\",\"serverDomain\":\"home.denone.flagship.services\",\"delegatedPubKey\":\"c86d01ad8b2fb694b22ff60e3c9d9e7ed90db5604772b74450d40913b9a9cbaf\",\"userPubKey\":\"8146640f02493af4fbc54fe33388e75dc2c937ae0b7727cc2b2afb1b75199a3e\",\"issuedAt\":1000,\"expiresAt\":99999999999999},\"authCodeUserSignature\":\"55555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555\",\"installerGitRef\":\"main\",\"rckPubKey\":\"ba42458e83ba7926ba8b8f3e9ab9caaf0f1c4918dda8c551084f7aeb1065b74b\",\"diskEncryption\":\"none\",\"blobSignatureHex\":\"31da15400225ae17acde21eb50bbe51f0b939754283c231e99c9edf307731d48899f5bf314278a5c58d81b093d550b53fd05c8917cb0b28481cf78f18759d002\"}";

    private static byte[] D(string s) => Encoding.UTF8.GetBytes(s);

    [Fact]
    public void AcceptsGoldenRecipe()
    {
        var r = RecipeLoader.Load(D(GoldenJson));
        Assert.Equal("home.golden.flagship.services", r.ServerDomain);
        Assert.Equal("golden", r.Username);
        Assert.Equal("home", r.ServerName);
        Assert.Equal("01GOLDENTEST", r.AuthCode.Serial);
    }

    [Fact]
    public void AcceptsIssuedEnvelopeForm()
    {
        // .com / the website hand out { blob, blobSignature }; the burner must
        // accept it, not only the flattened form.
        using var doc = JsonDocument.Parse(GoldenJson);
        var root = doc.RootElement;
        using var ms = new System.IO.MemoryStream();
        using (var w = new Utf8JsonWriter(ms))
        {
            w.WriteStartObject();
            w.WritePropertyName("blob");
            w.WriteStartObject();
            foreach (var p in root.EnumerateObject())
            {
                if (p.NameEquals("blobSignatureHex")) continue;
                p.WriteTo(w);
            }
            w.WriteEndObject();
            w.WriteString("blobSignature", root.GetProperty("blobSignatureHex").GetString());
            w.WriteEndObject();
        }
        var r = RecipeLoader.Load(ms.ToArray());
        Assert.Equal("home.golden.flagship.services", r.ServerDomain);
        Assert.Equal("01GOLDENTEST", r.AuthCode.Serial);
    }

    [Fact]
    public void RejectsTamperedSignature()
    {
        var bad = GoldenJson.Replace("cf239ce9", "ffffffff");
        var ex = Assert.Throws<RecipeException>(() => RecipeLoader.Load(D(bad)));
        Assert.Contains("signature", ex.Message);
    }

    [Fact]
    public void RejectsTamperedField()
    {
        // Flip the server domain — canonical bytes change, signature must fail.
        var bad = GoldenJson.Replace("home.golden.flagship.services", "home.evil.flagship.services");
        var ex = Assert.Throws<RecipeException>(() => RecipeLoader.Load(D(bad)));
        Assert.Contains("signature", ex.Message);
    }

    [Fact]
    public void RejectsExpired()
    {
        var future = DateTimeOffset.FromUnixTimeSeconds(4_200_000_000);
        var ex = Assert.Throws<RecipeException>(() => RecipeLoader.Load(D(GoldenJson), future));
        Assert.Contains("expired", ex.Message);
    }

    [Fact]
    public void RejectsWrongVersion()
    {
        var v1 = GoldenJson.Replace("\"version\": 2", "\"version\": 1");
        var ex = Assert.Throws<RecipeException>(() => RecipeLoader.Load(D(v1)));
        Assert.Contains("version 1", ex.Message);
    }

    [Fact]
    public void AcceptsApproveModeRecipe()
    {
        var r = RecipeLoader.Load(D(ApproveGoldenJson));
        Assert.Equal("approve", r.BootUnlockMode);
        Assert.Equal("approve", r.EffectiveBootUnlockMode);
    }

    [Fact]
    public void ApproveModeIsCovenantBySignature()
    {
        // Strip bootUnlockMode from a recipe whose signature COMMITTED to it —
        // canonical bytes change, so verification must fail (a relay/.com cannot
        // downgrade an "approve" server to "auto").
        var downgraded = ApproveGoldenJson.Replace(",\"bootUnlockMode\":\"approve\"", "");
        var ex = Assert.Throws<RecipeException>(() => RecipeLoader.Load(D(downgraded)));
        Assert.Contains("signature", ex.Message);
    }

    [Fact]
    public void AcceptsDiskEncryptionNoneRecipe()
    {
        var r = RecipeLoader.Load(D(DiskEncryptionNoneGoldenJson));
        Assert.Equal("home.denone.flagship.services", r.ServerDomain);
        Assert.Equal("none", r.DiskEncryption);
        // The burner consumes this: "none" ⇒ skip LUKS.
        Assert.False(r.EncryptsDisk);
    }

    [Fact]
    public void DiskEncryptionIsCovenantBySignature()
    {
        // Flip none→luks: canonical bytes become `de=luks`, so the committed
        // signature must fail — a relay can't downgrade/upgrade the encryption
        // posture a phone signed.
        var tampered = DiskEncryptionNoneGoldenJson.Replace("\"diskEncryption\":\"none\"", "\"diskEncryption\":\"luks\"");
        var ex1 = Assert.Throws<RecipeException>(() => RecipeLoader.Load(D(tampered)));
        Assert.Contains("signature", ex1.Message);
        // Stripping the field entirely (re-present a "none" recipe as legacy/
        // encrypted) must also fail.
        var stripped = DiskEncryptionNoneGoldenJson.Replace(",\"diskEncryption\":\"none\"", "");
        var ex2 = Assert.Throws<RecipeException>(() => RecipeLoader.Load(D(stripped)));
        Assert.Contains("signature", ex2.Message);
    }

    [Fact]
    public void AbsentDiskEncryptionDefaultsToEncrypted()
    {
        // The original golden recipe carries no diskEncryption ⇒ null ⇒ the box
        // encrypts (EncryptsDisk == true). Backward compatibility.
        var r = RecipeLoader.Load(D(GoldenJson));
        Assert.Null(r.DiskEncryption);
        Assert.True(r.EncryptsDisk);
    }

    [Fact]
    public void HexRoundTrip()
    {
        Assert.Equal("00ff10", Hex.Encode(Hex.Decode("00ff10")!));
        Assert.Null(Hex.Decode("xyz"));
        Assert.Null(Hex.Decode("abc")); // odd length
    }

    [Fact]
    public void GoldenRecipeReVerifiesUnderItsOwnCanonicalBytes()
    {
        // Re-deriving canonical bytes from the parsed recipe re-verifies — i.e.
        // a box receiving this recipe would accept it.
        var r = RecipeLoader.Load(D(GoldenJson));
        Assert.Equal("home.golden.flagship.services", r.ServerDomain);
        Assert.True(RecipeLoader.VerifySignature(r));
    }
}
