// Runs the SINGLE canonical preseed / user-data generator on Android, via
// Mozilla Rhino (pure-Java JS engine), proven byte-identical to Node + the
// macOS/iOS JavaScriptCore builder against the shared golden vectors.
//
// WHY a JS engine and not a Kotlin re-implementation: the preseed/bootstrap
// text is the security-critical signed-install path. It has exactly ONE
// implementation — `packages/flagship-builder/engine/preseed-engine.js` (an
// esbuild bundle of the canonical TypeScript, zero Node builtins) — run
// unchanged on every builder. Android ships a BYTE-IDENTICAL copy of that file
// as the asset `assets/preseed-engine.js`. It MUST stay in sync with the
// package file; `PreseedEngineTest` is the drift guard that fails the build if
// the asset ever diverges from `packages/flagship-builder/engine/preseed-engine.js`.
//
// The engine does NOT verify the recipe signature — the phone is the trust root
// and verifies natively before handing the recipe here (matching the desktop
// builder + the engine's documented contract).
//
// MANDATORY on ART: Rhino must run in INTERPRETED mode (optimizationLevel = -1).
// Its default compiling mode generates JVM bytecode at runtime, which fails on
// Android (no on-device class loading of generated bytecode).
//
// BUNDLE TARGET (see build.gradle.kts): the bundle MUST be lowered to es5 — Rhino
// mis-resolves a for-loop variable inside any loop body that contains a
// block-scoped (let/const) declaration, and `rhino-runtime` can't parse ES2015
// default params. An es5 bundle (no block scoping, no default params) runs
// byte-identical to Node on Rhino. The current canonical bundle is built
// --target=es2017, so the golden-vector tests fail until it is regenerated es5.

package com.flagshipserver.app.builder.iso

import org.mozilla.javascript.Function
import org.mozilla.javascript.Scriptable
import org.mozilla.javascript.ScriptableObject
import org.mozilla.javascript.Context as RhinoContext

class PreseedEngineException(message: String, cause: Throwable? = null) :
    RuntimeException(message, cause)

/**
 * Evaluates the canonical preseed-engine bundle and exposes its two entry
 * points. Construct with the bundle source for testability (the golden-vector
 * test feeds it the on-disk bundle directly); use [fromAssets] in the app.
 */
class PreseedEngine(private val bundleSource: String) {

    // The bundle attaches `FlagshipPreseed` to its global scope. We evaluate it
    // ONCE into a reusable scope (correctness-preserving + cheap to reuse): each
    // call re-enters a Rhino Context (Context is thread-bound, must be
    // entered/exited per use) but reuses the already-evaluated functions.
    @Volatile private var scope: Scriptable? = null

    private fun ensureScope(cx: RhinoContext): Scriptable {
        scope?.let { return it }
        synchronized(this) {
            scope?.let { return it }
            val s = cx.initStandardObjects()
            // The bundle's IIFE does `const g = globalThis; g.FlagshipPreseed = …`.
            // Guarantee `globalThis` resolves to the scope on every Rhino version.
            ScriptableObject.putProperty(s, "globalThis", s)
            try {
                cx.evaluateString(s, bundleSource, "preseed-engine.js", 1, null)
            } catch (t: Throwable) {
                throw PreseedEngineException("failed to evaluate preseed-engine bundle: ${t.message}", t)
            }
            val installed = ScriptableObject.getProperty(s, "FlagshipPreseed")
            if (installed !is Scriptable) {
                throw PreseedEngineException(
                    "bundle did not install global FlagshipPreseed (got $installed)",
                )
            }
            scope = s
            return s
        }
    }

    /** Debian d-i preseed.cfg for [recipeJson] (signed recipe) + [burnOptsJson]. */
    fun buildPreseedFromRecipe(recipeJson: String, burnOptsJson: String = "{}"): String =
        invoke("buildPreseedFromRecipe", recipeJson, burnOptsJson)

    /** Ubuntu autoinstall user-data for [recipeJson] + [burnOptsJson]. */
    fun buildUserDataFromRecipe(recipeJson: String, burnOptsJson: String = "{}"): String =
        invoke("buildUserDataFromRecipe", recipeJson, burnOptsJson)

    private fun invoke(method: String, recipeJson: String, burnOptsJson: String): String {
        val cx = RhinoContext.enter()
        try {
            // ART: interpreted only (no generated bytecode). ES6 for the bundle's
            // arrow fns / const-let / template literals / destructuring / spread.
            cx.optimizationLevel = -1
            cx.languageVersion = RhinoContext.VERSION_ES6
            val s = ensureScope(cx)
            val api = ScriptableObject.getProperty(s, "FlagshipPreseed") as Scriptable
            val fn = ScriptableObject.getProperty(api, method)
            if (fn !is Function) {
                throw PreseedEngineException("FlagshipPreseed.$method is not a function (got $fn)")
            }
            val result = try {
                fn.call(cx, s, api, arrayOf<Any?>(recipeJson, burnOptsJson))
            } catch (t: Throwable) {
                throw PreseedEngineException("FlagshipPreseed.$method threw: ${t.message}", t)
            }
            if (result == null || result == RhinoContext.getUndefinedValue()) {
                throw PreseedEngineException("FlagshipPreseed.$method returned no string")
            }
            return RhinoContext.toString(result)
        } finally {
            RhinoContext.exit()
        }
    }

    companion object {
        const val ASSET_NAME = "preseed-engine.js"

        /**
         * Load the engine from the app's bundled asset
         * (`assets/preseed-engine.js`, a byte-identical copy of
         * `packages/flagship-builder/engine/preseed-engine.js`).
         */
        fun fromAssets(context: android.content.Context): PreseedEngine {
            val src = context.assets.open(ASSET_NAME).use { it.readBytes().toString(Charsets.UTF_8) }
            return PreseedEngine(src)
        }
    }
}
