package com.flagship.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavController
import com.flagship.ui.components.FSCard
import com.flagship.ui.components.FSField
import com.flagship.ui.components.FSGhostButton
import com.flagship.ui.components.FSPrimaryButton
import com.flagship.ui.theme.FS

/**
 * D.3.7 + D.3.8 — BYOH form + BuildCodeDisplayView combined as a
 * two-state screen. Generate a build code locally (signed by IRK),
 * display QR + 20-char base32. Polls for the box coming online.
 */
@Composable
fun BuildCodeScreen(nav: NavController) {
    var serverName by remember { mutableStateOf("home") }
    var generated by remember { mutableStateOf<GeneratedCode?>(null) }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(horizontal = FS.space.s6),
    ) {
        Spacer(Modifier.height(FS.space.s12))

        if (generated == null) {
            Text(
                text = "Build code",
                color = FS.colors.text,
                style = TextStyle(fontSize = 28.sp, lineHeight = 36.sp, fontWeight = FontWeight.Medium),
            )
            Spacer(Modifier.height(FS.space.s4))
            Text(
                text = "Pick a name for this server. We'll generate a one-time code; paste it at flagshipserver.com/build to download a personalized installer.",
                color = FS.colors.textMuted,
                style = TextStyle(fontSize = 16.sp, lineHeight = 24.sp),
            )
            Spacer(Modifier.height(FS.space.s8))

            FSField(
                value = serverName,
                onValueChange = { serverName = it.lowercase() },
                label = "Server name",
                placeholder = "home",
                helper = "Becomes the leftmost part of the URL: <name>.harry.flagship.services",
            )

            Spacer(Modifier.height(FS.space.s8))

            FSPrimaryButton(
                label = "Generate code",
                onClick = {
                    generated = GeneratedCode(
                        // TODO: real IRK-signed AuthCode + 24h expiry
                        code = "PR8K-D9XM-2Q4F-7TY2-NW3E",
                        url = "flagshipserver.com/build",
                    )
                },
                block = true,
                large = true,
                enabled = serverName.isNotBlank(),
            )
        } else {
            Text(
                text = "Your code is ready.",
                color = FS.colors.text,
                style = TextStyle(fontSize = 28.sp, lineHeight = 36.sp, fontWeight = FontWeight.Medium),
            )
            Spacer(Modifier.height(FS.space.s4))
            Text(
                text = "Paste this at flagshipserver.com/build, download the installer, and flash it to a USB.",
                color = FS.colors.textMuted,
                style = TextStyle(fontSize = 16.sp, lineHeight = 24.sp),
            )
            Spacer(Modifier.height(FS.space.s8))

            // QR placeholder — real implementation uses ZXing
            FSCard(padding = PaddingValues(FS.space.s6)) {
                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(220.dp)
                        .clip(RoundedCornerShape(FS.radius.sm))
                        .background(FS.colors.surfaceSunken)
                        .border(1.dp, FS.colors.border, RoundedCornerShape(FS.radius.sm)),
                    contentAlignment = Alignment.Center,
                ) {
                    Text("QR will render here", color = FS.colors.textMuted)
                }
                Spacer(Modifier.height(FS.space.s4))
                Text(
                    text = generated!!.code,
                    color = FS.colors.text,
                    style = TextStyle(
                        fontSize = 20.sp,
                        lineHeight = 28.sp,
                        fontWeight = FontWeight.SemiBold,
                        fontFamily = androidx.compose.ui.text.font.FontFamily.Monospace,
                    ),
                )
                Spacer(Modifier.height(FS.space.s2))
                Text(
                    text = generated!!.url,
                    color = FS.colors.textMuted,
                    style = TextStyle(fontSize = 14.sp, fontFamily = androidx.compose.ui.text.font.FontFamily.Monospace),
                )
            }

            Spacer(Modifier.height(FS.space.s6))

            Text(
                text = "Once your box is online, this screen will switch to a celebratory \"Your Flagship is online.\" state.",
                color = FS.colors.textMuted,
                style = TextStyle(fontSize = 14.sp, lineHeight = 20.sp),
            )

            Spacer(Modifier.height(FS.space.s8))

            FSGhostButton(
                label = "Cancel",
                onClick = { generated = null },
                block = true,
            )
        }
    }
}

private data class GeneratedCode(val code: String, val url: String)
