import XCTest
import CryptoKit
import FlagshipAPI
@testable import FlagshipCore

/// iOS half of the shared canonical-bytes contract — mirror of the TS, webapp,
/// and Kotlin tests. Loads THE single authoritative fixture,
/// `test-vectors/canonical-bytes.json` (generated by `tools/test-vectors.ts`),
/// from disk at test time. The file is located via `#filePath` (this source's
/// compile-time path) walked up to the repo root — so NO Package.swift
/// `resources:` copy is needed and the vectors are never transcribed into Swift
/// literals. For every purpose the iOS client implements it:
///   1. recomputes the canonical bytes via the REAL Swift `canonicalBytes()`
///      and asserts byte-equality with the recorded `canonicalHex`, and
///   2. verifies the recorded Ed25519 signature under the recorded signer pub.
/// A divergence between iOS and the source surfaces HERE rather than as a live
/// cross-platform "phone signs, .com/box rejects" signature failure. Purposes
/// iOS doesn't implement are skipped-with-note (counted, not silently dropped).
final class CanonicalBytesVectorsTests: XCTestCase {

    // MARK: fixture loading

    private struct Loaded {
        let metadata: [String: Any]
        let vectors: [[String: Any]]
    }

    /// Walk up from this source file to find `test-vectors/canonical-bytes.json`.
    private func locateFixture() -> URL? {
        var dir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        for _ in 0..<12 {
            let candidate = dir
                .appendingPathComponent("test-vectors")
                .appendingPathComponent("canonical-bytes.json")
            if FileManager.default.fileExists(atPath: candidate.path) {
                return candidate
            }
            dir = dir.deletingLastPathComponent()
        }
        return nil
    }

    private func load() throws -> Loaded {
        guard let url = locateFixture() else {
            XCTFail("could not locate test-vectors/canonical-bytes.json from \(#filePath)")
            throw NSError(domain: "fixture", code: 1)
        }
        let data = try Data(contentsOf: url)
        let root = try JSONSerialization.jsonObject(with: data) as! [String: Any]
        let metadata = root["metadata"] as! [String: Any]
        let vectors = root["vectors"] as! [[String: Any]]
        return Loaded(metadata: metadata, vectors: vectors)
    }

    // MARK: helpers

    private func unhex(_ h: String) -> Data { HexUtil.decode(h)! }

    private func verifies(_ sig: Data, _ bytes: Data, _ pub: Data) -> Bool {
        guard let key = try? Curve25519.Signing.PublicKey(rawRepresentation: pub) else { return false }
        return key.isValidSignature(sig, for: bytes)
    }

    private func pub(_ meta: [String: Any], _ signedBy: String) -> Data {
        switch signedBy {
        case "irk": return unhex(meta["irkPubHex"] as! String)
        case "old-irk": return unhex(meta["oldIrkPubHex"] as! String)
        case "bak": return unhex(meta["bakPubHex"] as! String)
        case "stk": return unhex(meta["stkPubHex"] as! String)
        case "rck": return unhex(meta["rckPubHex"] as! String)
        case "identity": return unhex(meta["identityPubHex"] as! String)
        default: return Data()
        }
    }

    /// Read an Int64 from a JSON number (NSNumber) regardless of how
    /// JSONSerialization boxed it.
    private func i64(_ i: [String: Any], _ key: String) -> Int64 {
        (i[key] as! NSNumber).int64Value
    }

    // MARK: the purposes iOS implements → recompute canonical bytes

    private func canonical(_ name: String, _ i: [String: Any]) -> Data? {
        switch name {
        case "revoke":
            return ServerRevocationClaim.canonicalBytes(
                userId: i["userId"] as! String,
                revokedServerId: i["revokedServerId"] as! String,
                reason: i["reason"] as! String,
                issuedAt: i64(i, "issuedAt")
            )
        case "auth-code":
            return AuthCode(
                version: 1,
                serial: i["serial"] as! String,
                username: i["username"] as! String,
                serverName: i["serverName"] as! String,
                serverDomain: i["serverDomain"] as! String,
                delegatedPubKey: unhex(i["delegatedPubKey"] as! String),
                userPubKey: unhex(i["userPubKey"] as! String),
                issuedAt: i64(i, "issuedAt"),
                expiresAt: i64(i, "expiresAt")
            ).canonicalBytes()
        case "install-blob":
            let authCode = AuthCode(
                version: 1,
                serial: i["authCodeSerial"] as! String,
                username: i["username"] as! String,
                serverName: i["serverName"] as! String,
                serverDomain: i["serverDomain"] as! String,
                delegatedPubKey: Data(),
                userPubKey: unhex(i["authCodeUserPubKey"] as! String),
                issuedAt: 0,
                expiresAt: 0
            )
            return InstallBlob(
                version: Int((i["version"] as! NSNumber).intValue),
                serverDomain: i["serverDomain"] as! String,
                username: i["username"] as! String,
                serverName: i["serverName"] as! String,
                phoneDelegatedPubKey: unhex(i["phoneDelegatedPubKey"] as! String),
                registrationUrl: i["registrationUrl"] as! String,
                authCode: authCode,
                authCodeUserSignature: unhex(i["authCodeUserSignature"] as! String),
                installerGitRef: i["installerGitRef"] as! String,
                rckPubKey: unhex(i["rckPubKey"] as! String),
                bootUnlockMode: i["bootUnlockMode"] as? String,
                diskEncryption: i["diskEncryption"] as? String
            ).canonicalBytes()
        case "order-set-front-page":
            return SetFrontPageOrder(
                serverId: i["serverId"] as! String,
                label: i["label"] as! String,
                issuedAt: i64(i, "issuedAt")
            ).canonicalBytes()
        case "order-power-off-off", "order-power-off-restart":
            return PowerOffOrder(
                serverId: i["serverId"] as! String,
                mode: PowerMode(rawValue: i["mode"] as! String)!,
                issuedAt: i64(i, "issuedAt")
            ).canonicalBytes()
        case "journal-read":
            return JournalRequest(
                serverId: i["serverId"] as! String,
                unit: i["unit"] as! String,
                lines: i64(i, "lines"),
                issuedAt: i64(i, "issuedAt")
            ).canonicalBytes()
        case "watch-delegate-key":
            return WatchDelegateKeyEnvelope(
                grantId: i["grantId"] as! String,
                username: i["username"] as! String,
                delegatePubKeyHex: i["delegatePubKey"] as! String,
                scopes: i["scopes"] as! [String],
                issuedAt: i64(i, "issuedAt"),
                expiresAt: i64(i, "expiresAt")
            ).canonicalBytes()
        case "device-capability-grant":
            return DeviceCapabilityGrantEnvelope(
                grantId: i["grantId"] as! String,
                username: i["username"] as! String,
                deviceLabel: i["deviceLabel"] as! String,
                devicePubKeyHex: i["devicePubKey"] as! String,
                scopes: i["scopes"] as! [String],
                issuedAt: i64(i, "issuedAt"),
                expiresAt: i64(i, "expiresAt")
            ).canonicalBytes()
        case "push-token-revoke":
            return PushTokenRevoke.canonicalBytes(
                tokenId: i["tokenId"] as! String,
                issuedAt: i64(i, "issuedAt")
            )
        case "re-pair-initiate":
            return RePairInitiate.canonicalBytes(
                username: i["username"] as! String,
                newIrkPubHex: i["newIrkPub"] as! String,
                oldIrkPubHex: i["oldIrkPub"] as! String,
                issuedAt: i64(i, "issuedAt")
            )
        case "daemon-status", "daemon-status-liveness":
            let report = DaemonStatusReport(
                serverDomain: i["serverDomain"] as! String,
                certSha256: i["certSha256"] as? String,
                certValidUntil: (i["certValidUntil"] as? NSNumber)?.int64Value,
                certIssuer: i["certIssuer"] as? String,
                appsServed: i["appsServed"] as! [String],
                nonce: i["nonce"] as! String,
                issuedAt: i64(i, "issuedAt")
            )
            return DaemonStatus.canonicalBytes(report)
        default:
            return nil
        }
    }

    /// The exact set of purposes this test claims to cover, so a regression
    /// that drops one (e.g. a removed `case`) is caught by the count below.
    private let coveredNames: Set<String> = [
        "revoke", "auth-code", "install-blob", "order-set-front-page",
        "order-power-off-off", "order-power-off-restart", "journal-read",
        "watch-delegate-key", "device-capability-grant", "push-token-revoke",
        "re-pair-initiate", "daemon-status", "daemon-status-liveness",
    ]

    func testEveryIosImplementedVectorMatchesTheSharedFixture() throws {
        let loaded = try load()
        let names = Set(loaded.vectors.map { $0["name"] as! String })

        // Every name this test claims to cover must exist in the fixture.
        for n in coveredNames {
            XCTAssertTrue(names.contains(n), "covered name '\(n)' missing from the fixture")
        }

        var asserted = 0
        var skipped = 0
        for v in loaded.vectors {
            let name = v["name"] as! String
            let input = v["input"] as! [String: Any]
            guard let bytes = canonical(name, input) else {
                XCTAssertFalse(coveredNames.contains(name), "\(name) is covered but produced no bytes")
                skipped += 1
                continue
            }
            XCTAssertTrue(coveredNames.contains(name), "\(name) produced bytes but isn't in coveredNames")
            XCTAssertEqual(
                HexUtil.encode(bytes),
                v["canonicalHex"] as! String,
                "canonical bytes drift for \(name)"
            )
            let signedBy = v["signedBy"] as! String
            if signedBy != "none" {
                let sig = unhex(v["signatureHex"] as! String)
                XCTAssertTrue(
                    verifies(sig, bytes, pub(loaded.metadata, signedBy)),
                    "signature for \(name) does not verify under \(signedBy) pub"
                )
            }
            asserted += 1
        }
        XCTAssertEqual(asserted, coveredNames.count, "did not assert every covered purpose")
        XCTAssertGreaterThan(skipped, 0, "expected some purposes to be skipped-by-design")
    }
}
