import XCTest
import CryptoKit
@testable import Flagship
@testable import FlagshipCore

final class InstallBlobTests: XCTestCase {

    // MARK: - Canonical bytes

    func test_installBlobCanonicalBytes_followsPipeSeparatedV1Format() {
        let auth = AuthCode(
            serial: "01ABCD",
            username: "harry",
            serverName: "home",
            serverDomain: "home.harry.flagship.services",
            delegatedPubKey: Data(repeating: 0x11, count: 32),
            userPubKey: Data(repeating: 0x22, count: 32),
            issuedAt: 1,
            expiresAt: 2
        )
        let blob = InstallBlob(
            serverDomain: "home.harry.flagship.services",
            username: "harry",
            serverName: "home",
            phoneDelegatedPubKey: Data(repeating: 0x33, count: 32),
            authCode: auth,
            authCodeUserSignature: Data(repeating: 0x44, count: 64),
            rckPubKey: Data(repeating: 0x55, count: 32)
        )
        let s = String(data: blob.canonicalBytes(), encoding: .utf8)!
        // Must start with the canonical tag, must be pipe-separated.
        // v2: blob.issuedAt+expiresAt dropped; tag stays v1.
        XCTAssertTrue(s.hasPrefix("flagship/install-blob/v1|2|home.harry.flagship.services|harry|home|"))
        XCTAssertTrue(s.contains("\(String(repeating: "33", count: 32))|"))   // phoneDelegatedPubKey hex
        XCTAssertTrue(s.contains("|01ABCD|"))                                  // authCode serial
        XCTAssertTrue(s.contains("|\(String(repeating: "55", count: 32))"))   // rckPubKey trailing
    }

    func test_installBlobCanonicalBytes_bootUnlockModeAppendedOnlyWhenPresent() {
        let auth = AuthCode(
            serial: "01ABCD",
            username: "harry",
            serverName: "home",
            serverDomain: "home.harry.flagship.services",
            delegatedPubKey: Data(repeating: 0x11, count: 32),
            userPubKey: Data(repeating: 0x22, count: 32),
            issuedAt: 1,
            expiresAt: 2
        )
        func blob(_ mode: String?) -> InstallBlob {
            InstallBlob(
                serverDomain: "home.harry.flagship.services",
                username: "harry",
                serverName: "home",
                phoneDelegatedPubKey: Data(repeating: 0x33, count: 32),
                authCode: auth,
                authCodeUserSignature: Data(repeating: 0x44, count: 64),
                rckPubKey: Data(repeating: 0x55, count: 32),
                bootUnlockMode: mode
            )
        }
        let rck = String(repeating: "55", count: 32)
        // Absent ⇒ exact legacy bytes (canonical ends at rckPubKey).
        XCTAssertTrue(String(data: blob(nil).canonicalBytes(), encoding: .utf8)!.hasSuffix("|\(rck)"))
        // Present ⇒ appended as the final field.
        XCTAssertTrue(String(data: blob("approve").canonicalBytes(), encoding: .utf8)!.hasSuffix("|\(rck)|approve"))
        XCTAssertTrue(String(data: blob("auto").canonicalBytes(), encoding: .utf8)!.hasSuffix("|auto"))
    }

    func test_installBlobCanonicalBytes_diskEncryptionAppendedLastOnlyWhenPresent() {
        let auth = AuthCode(
            serial: "01ABCD", username: "harry", serverName: "home",
            serverDomain: "home.harry.flagship.services",
            delegatedPubKey: Data(repeating: 0x11, count: 32),
            userPubKey: Data(repeating: 0x22, count: 32), issuedAt: 1, expiresAt: 2
        )
        func blob(
            _ de: String?,
            boot: String? = nil
        ) -> InstallBlob {
            InstallBlob(
                serverDomain: "home.harry.flagship.services", username: "harry", serverName: "home",
                phoneDelegatedPubKey: Data(repeating: 0x33, count: 32), authCode: auth,
                authCodeUserSignature: Data(repeating: 0x44, count: 64),
                rckPubKey: Data(repeating: 0x55, count: 32),
                bootUnlockMode: boot, diskEncryption: de
            )
        }
        func canon(_ b: InstallBlob) -> String { String(data: b.canonicalBytes(), encoding: .utf8)! }
        let rck = String(repeating: "55", count: 32)
        // Absent ⇒ exact legacy bytes (no de= token).
        XCTAssertTrue(canon(blob(nil)).hasSuffix("|\(rck)"))
        // Present ⇒ `de=<mode>` — MUST match TS `de=${b.diskEncryption}`.
        XCTAssertTrue(canon(blob("none")).hasSuffix("|de=none"))
        XCTAssertTrue(canon(blob("luks")).hasSuffix("|de=luks"))
        // Appended LAST — after bootUnlockMode.
        XCTAssertTrue(
            canon(blob("none", boot: "approve"))
                .hasSuffix("|approve|de=none")
        )
    }

    // Byte-identity proof against @flagship/protocol signInstallBlob. The
    // golden recipe carries diskEncryption:"none"; the signature commits to the
    // trailing `de=none`. Generated by packages/protocol with fixed seeds
    // (userPubKey 8146…9a3e). If iOS's canonicalBytes dropped or mis-spelled
    // the `de=` append, the signature would NOT verify. Do not hand-edit.
    private static let diskEncryptionNoneUserPubHex =
        "8146640f02493af4fbc54fe33388e75dc2c937ae0b7727cc2b2afb1b75199a3e"
    private static let diskEncryptionNoneSigHex =
        "31da15400225ae17acde21eb50bbe51f0b939754283c231e99c9edf307731d48" +
        "899f5bf314278a5c58d81b093d550b53fd05c8917cb0b28481cf78f18759d002"

    /// Rebuilds the golden recipe's InstallBlob (diskEncryption: "none").
    private func diskEncryptionNoneGoldenBlob() -> InstallBlob {
        let userPub = HexUtil.decode(Self.diskEncryptionNoneUserPubHex)!
        let delegated = HexUtil.decode(
            "c86d01ad8b2fb694b22ff60e3c9d9e7ed90db5604772b74450d40913b9a9cbaf"
        )!
        let auth = AuthCode(
            version: 1,
            serial: "01DENONE0001",
            username: "denone",
            serverName: "home",
            serverDomain: "home.denone.flagship.services",
            delegatedPubKey: delegated,
            userPubKey: userPub,
            issuedAt: 1000,
            expiresAt: 99_999_999_999_999
        )
        return InstallBlob(
            version: 2,
            serverDomain: "home.denone.flagship.services",
            username: "denone",
            serverName: "home",
            phoneDelegatedPubKey: delegated,
            registrationUrl: "https://flagshipserver.com/api/server/register",
            authCode: auth,
            authCodeUserSignature: Data(repeating: 0x55, count: 64),
            installerGitRef: "main",
            rckPubKey: HexUtil.decode(
                "ba42458e83ba7926ba8b8f3e9ab9caaf0f1c4918dda8c551084f7aeb1065b74b"
            )!,
            diskEncryption: "none"
        )
    }

    func test_diskEncryptionNone_goldenSignatureVerifiesAgainstCanonicalBytes() throws {
        let blob = diskEncryptionNoneGoldenBlob()
        let pub = try Curve25519.Signing.PublicKey(
            rawRepresentation: HexUtil.decode(Self.diskEncryptionNoneUserPubHex)!
        )
        let sig = HexUtil.decode(Self.diskEncryptionNoneSigHex)!
        // The @flagship/protocol signature verifies against the iOS canonical
        // bytes ⇒ the `de=none` append is byte-identical across TS + Swift.
        XCTAssertTrue(
            pub.isValidSignature(sig, for: blob.canonicalBytes()),
            "iOS canonicalBytes(de=none) must match @flagship/protocol byte-for-byte"
        )
    }

    func test_diskEncryption_isCovenantBySignature_flipOrStripFails() throws {
        let pub = try Curve25519.Signing.PublicKey(
            rawRepresentation: HexUtil.decode(Self.diskEncryptionNoneUserPubHex)!
        )
        let sig = HexUtil.decode(Self.diskEncryptionNoneSigHex)!

        // Flip none→luks: canonical bytes become `de=luks`, so the signature
        // committed over `de=none` must fail — a relay can't downgrade/upgrade
        // the encryption posture a phone signed.
        var flipped = diskEncryptionNoneGoldenBlob()
        flipped.diskEncryption = "luks"
        XCTAssertFalse(pub.isValidSignature(sig, for: flipped.canonicalBytes()))

        // Stripping the field entirely (re-present a "none" recipe as legacy/
        // encrypted) must also fail — the trailing `de=none` is gone.
        var stripped = diskEncryptionNoneGoldenBlob()
        stripped.diskEncryption = nil
        XCTAssertFalse(pub.isValidSignature(sig, for: stripped.canonicalBytes()))
    }

    func test_authCodeCanonicalBytes_followsV1Format() {
        let auth = AuthCode(
            serial: "01XYZ",
            username: "harry",
            serverName: "home",
            serverDomain: "home.harry.flagship.services",
            delegatedPubKey: Data(repeating: 0x11, count: 32),
            userPubKey: Data(repeating: 0x22, count: 32),
            issuedAt: 1234,
            expiresAt: 5678
        )
        let s = String(data: auth.canonicalBytes(), encoding: .utf8)!
        XCTAssertEqual(
            s,
            "flagship/auth-code/v1|1|01XYZ|harry|home|home.harry.flagship.services|" +
            String(repeating: "11", count: 32) + "|" +
            String(repeating: "22", count: 32) + "|1234|5678"
        )
    }

    func test_usernameClaimCanonicalBytes_followsV1Format() {
        let s = String(
            data: UsernameClaim.canonicalBytes(username: "harry", irkPubHex: "abcd", issuedAt: 42),
            encoding: .utf8
        )!
        XCTAssertEqual(s, "flagship/claim-username/v1|harry|abcd|42")
    }

    func test_pushTokenRegisterCanonicalBytes_followsV1Format() {
        let s = String(
            data: PushTokenRegister.canonicalBytes(
                username: "harry",
                platform: "apns",
                providerToken: "deadbeef",
                pushX25519PubHex: String(repeating: "ab", count: 32),
                label: "Harry's iPhone",
                issuedAt: 1700000000
            ),
            encoding: .utf8
        )!
        // Field order: tag | username | platform | providerToken |
        // pushX25519Pub | label | issuedAt. Mirrors the Worker side
        // in packages/protocol/src/auth.ts.
        XCTAssertEqual(
            s,
            "flagship/push-token-register/v1|harry|apns|deadbeef|" +
            String(repeating: "ab", count: 32) + "|Harry's iPhone|1700000000"
        )
    }

    func test_pushTokenRevokeCanonicalBytes_followsV1Format() {
        let s = String(
            data: PushTokenRevoke.canonicalBytes(
                tokenId: "0123456789abcdef0123456789abcdef",
                issuedAt: 1700000000000
            ),
            encoding: .utf8
        )!
        // Field order: tag | tokenId | issuedAt. Mirrors the Worker side
        // (canonicalPushTokenRevoke) in packages/protocol/src/auth.ts.
        XCTAssertEqual(
            s,
            "flagship/push-token-revoke/v1|0123456789abcdef0123456789abcdef|1700000000000"
        )
    }

    /// Cross-platform signature vector: a fixed Ed25519 seed signing the
    /// revoke canonical bytes MUST produce the SAME signature the TS
    /// (`packages/protocol/tests/pushTokenRevoke.test.ts`) and Kotlin
    /// mirrors pin. Ed25519 is deterministic so this is exact.
    func test_pushTokenRevoke_pinnedSignatureVector() throws {
        let seed = Data(repeating: 0x11, count: 32)
        let key = try Curve25519.Signing.PrivateKey(rawRepresentation: seed)
        let bytes = PushTokenRevoke.canonicalBytes(
            tokenId: "0123456789abcdef0123456789abcdef",
            issuedAt: 1700000000000
        )
        let sigHex = try key.signature(for: bytes).map { String(format: "%02x", $0) }.joined()
        XCTAssertEqual(
            sigHex,
            "46dde40edd081692a6412539bbb5e1a27f978a0bfdd27bbbd7cd4911501f5c27" +
            "3948f78248c70199ccb27905720a5a22fe5dc9d7c4bbff2b936663a467f2980b"
        )
        // And the matching public key (so the verifier-side vector aligns).
        let pubHex = key.publicKey.rawRepresentation.map { String(format: "%02x", $0) }.joined()
        XCTAssertEqual(
            pubHex,
            "d04ab232742bb4ab3a1368bd4615e4e6d0224ab71a016baf8520a332c9778737"
        )
    }

    func test_authCodeRevokeCanonicalBytes_followsV1Format() {
        let s = String(
            data: AuthCodeRevoke.canonicalBytes(serial: "01ABCD", username: "harry", issuedAt: 7),
            encoding: .utf8
        )!
        XCTAssertEqual(s, "flagship/auth-code-revoke/v1|01ABCD|harry|7")
    }

    func test_rckRegisterCanonicalBytes_followsV1Format() {
        let s = String(
            data: RckRegister.canonicalBytes(
                username: "harry",
                subdomain: "home.harry.flagship.services",
                rckPubHex: "deadbeef",
                issuedAt: 99
            ),
            encoding: .utf8
        )!
        XCTAssertEqual(s, "flagship/rck-register/v1|harry|home.harry.flagship.services|deadbeef|99")
    }

    // MARK: - Signing round-trip

    func test_signedInstallBlobVerifiesUnderIrkPublic() throws {
        let irk = Curve25519.Signing.PrivateKey()
        let auth = AuthCode(
            serial: "01CAFE",
            username: "harry",
            serverName: "home",
            serverDomain: "home.harry.flagship.services",
            delegatedPubKey: Data(repeating: 0x10, count: 32),
            userPubKey: irk.publicKey.rawRepresentation,
            issuedAt: 1,
            expiresAt: 2
        )
        let blob = InstallBlob(
            serverDomain: "home.harry.flagship.services",
            username: "harry",
            serverName: "home",
            phoneDelegatedPubKey: Data(repeating: 0x10, count: 32),
            authCode: auth,
            authCodeUserSignature: try irk.signature(for: auth.canonicalBytes()),
            rckPubKey: Data(repeating: 0x50, count: 32)
        )
        let sig = try irk.signature(for: blob.canonicalBytes())
        XCTAssertTrue(irk.publicKey.isValidSignature(sig, for: blob.canonicalBytes()))
    }

    // MARK: - HexUtil + SerialGen

    func test_hexRoundTrip() {
        let raw = Data((0..<256).map { UInt8($0) })
        let hex = HexUtil.encode(raw)
        XCTAssertEqual(hex.count, 512)
        XCTAssertEqual(HexUtil.decode(hex), raw)
    }

    func test_hexDecodeRejectsOddLengthAndNonHex() {
        XCTAssertNil(HexUtil.decode("abc"))
        XCTAssertNil(HexUtil.decode("zz"))
    }

    func test_serialGen_returnsExactly22HexCharsPrefixed01() {
        // Matches genSerial() in create-server.js — "01" + 10 random
        // bytes hexlified = 22 chars (the `.slice(0, 26)` in JS is a
        // no-op at that length).
        for _ in 0..<10 {
            let s = SerialGen.random()
            XCTAssertEqual(s.count, 22)
            XCTAssertTrue(s.hasPrefix("01"))
            XCTAssertNotNil(HexUtil.decode(s.lowercased()))
        }
    }
}
