using System.IO;
using System.Text.RegularExpressions;
namespace Flagship.Builder;
public enum IsoFamily { Ubuntu, Debian }
public static partial class NativeIsoRemaster
{
 public const string DebianPreseedCommandLine="auto=true priority=critical preseed/file=/cdrom/preseed.cfg";
 public static string ToXorrisoDiskPath(string p,bool windows=true){if(!windows)return p;var m=Drive().Match(p);return m.Success?$"/{char.ToLowerInvariant(m.Groups[1].Value[0])}/{m.Groups[2].Value.Replace('\\','/')}":p.Replace('\\','/');}
 public static IsoFamily ClassifyIsoText(string text){var t=text.ToLowerInvariant();if(Debian().IsMatch(t)){if(Ubuntu().IsMatch(t)&&!StrongDebian().IsMatch(t))return IsoFamily.Ubuntu;return IsoFamily.Debian;}return IsoFamily.Ubuntu;}
 public static string EditGrubForAutoinstall(string cfg){var lines=cfg.Split('\n').Select(l=>Linux().IsMatch(l)&&l.Contains("/casper/vmlinuz",StringComparison.Ordinal)&&!l.Contains("autoinstall",StringComparison.Ordinal)?Casper().Replace(l,"$1 autoinstall ds=nocloud\\;s=/cdrom/nocloud/"):l);return SetTimeout(string.Join("\n",lines));}
 public static string EditGrubForPreseed(string cfg){var lines=cfg.Split('\n').Select(l=>Linux().IsMatch(l)&&DebianKernel().IsMatch(l)&&!HasPreseed(l)?DebianToken().Replace(l,$"$1 {DebianPreseedCommandLine}"):l);return TimeoutStyle().Replace(SetTimeout(string.Join("\n",lines)),"set timeout_style=menu");}
 public static string EditIsolinuxForPreseed(string cfg){var lines=cfg.Split('\n').Select(l=>Append().IsMatch(l)&&Initrd().IsMatch(l)&&!HasPreseed(l)?Initrd().Replace(l,$"$1 {DebianPreseedCommandLine}"):l);var o=string.Join("\n",lines);o=SysTimeout().IsMatch(o)?SysTimeout().Replace(o,"${1}1"):$"timeout 1\n{o}";return Prompt().Replace(o,"prompt 0");}
 static bool HasPreseed(string l)=>l.Contains("preseed/file=/cdrom/preseed.cfg",StringComparison.Ordinal);
 static string SetTimeout(string s)=>GrubTimeout().IsMatch(s)?GrubTimeout().Replace(s,"set timeout=1"):$"set timeout=1\n{s}";
 [GeneratedRegex("^([A-Za-z]):[\\\\/](.*)$")]private static partial Regex Drive();
 [GeneratedRegex(@"\binstall\.amd\b|/d-i/|debian-installer|\bdebian\b",RegexOptions.IgnoreCase)]private static partial Regex Debian();
 [GeneratedRegex(@"\bcasper\b|\bubuntu\b",RegexOptions.IgnoreCase)]private static partial Regex Ubuntu();
 [GeneratedRegex(@"\binstall\.amd\b|/d-i/",RegexOptions.IgnoreCase)]private static partial Regex StrongDebian();
 [GeneratedRegex(@"^\s*linux\b")]private static partial Regex Linux();
 [GeneratedRegex(@"(/casper/vmlinuz\S*)")]private static partial Regex Casper();
 [GeneratedRegex(@"/install(\.amd)?/(gtk/)?(vmlinuz|linux)")]private static partial Regex DebianKernel();
 [GeneratedRegex(@"(linux\s+/install(?:\.amd)?/(?:gtk/)?(?:vmlinuz|linux)\S*)")]private static partial Regex DebianToken();
 [GeneratedRegex(@"^\s*append\b")]private static partial Regex Append();
 [GeneratedRegex(@"(initrd=\S*initrd\.gz)")]private static partial Regex Initrd();
 [GeneratedRegex(@"set\s+timeout=\d+")]private static partial Regex GrubTimeout();
 [GeneratedRegex(@"set\s+timeout_style=\w+")]private static partial Regex TimeoutStyle();
 [GeneratedRegex(@"^(\s*timeout\s+)\d+",RegexOptions.Multiline)]private static partial Regex SysTimeout();
 [GeneratedRegex(@"^\s*prompt\s+\d+",RegexOptions.Multiline)]private static partial Regex Prompt();
 public static string ResolveXorriso(string? value=null){if(!string.IsNullOrWhiteSpace(value))return value;var env=Environment.GetEnvironmentVariable("FLAGSHIP_XORRISO");if(!string.IsNullOrWhiteSpace(env))return env;var app=Path.Combine(AppContext.BaseDirectory,"tools","xorriso.exe");if(File.Exists(app))return app;const string msys=@"C:\msys64\usr\bin\xorriso.exe";return File.Exists(msys)?msys:"xorriso";}
 public static async Task<IsoFamily> DetectFamilyAsync(string iso,string? tool=null,CancellationToken ct=default){var x=ResolveXorriso(tool);var toc=await RunAsync(x,["-indev",Disk(iso),"-toc"],false,ct);if(toc.Contains("debian",StringComparison.OrdinalIgnoreCase))return IsoFamily.Debian;if(toc.Contains("ubuntu",StringComparison.OrdinalIgnoreCase))return IsoFamily.Ubuntu;var tree=await RunAsync(x,["-indev",Disk(iso),"-find","/","-maxdepth","2","-type","d"],false,ct);return ClassifyIsoText(toc+"\n"+tree);}
 public static async Task RemasterAsync(string source,string output,string preseed,string userData,string? tool=null,CancellationToken ct=default){var fi=new FileInfo(source);if(!fi.Exists||fi.Length<1024)throw new InvalidDataException("source ISO is missing or too small");var x=ResolveXorriso(tool);var family=await DetectFamilyAsync(source,x,ct);var work=Path.Combine(Path.GetTempPath(),"flagship-remaster-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(work);try{if(File.Exists(output))File.Delete(output);if(family==IsoFamily.Ubuntu)await Ubuntu(x,source,output,userData,work,ct);else await DebianIso(x,source,output,preseed,work,ct);}finally{try{Directory.Delete(work,true);}catch{}}}
 static async Task Ubuntu(string x,string src,string dst,string data,string work,CancellationToken ct){var grub=Path.Combine(work,"grub.cfg");await RunAsync(x,["-osirrox","on","-indev",Disk(src),"-extract","/boot/grub/grub.cfg",Disk(grub)],true,ct);await File.WriteAllTextAsync(grub,EditGrubForAutoinstall(await File.ReadAllTextAsync(grub,ct)),new System.Text.UTF8Encoding(false),ct);var seed=Path.Combine(work,"nocloud");Directory.CreateDirectory(seed);await File.WriteAllTextAsync(Path.Combine(seed,"user-data"),data,new System.Text.UTF8Encoding(false),ct);await File.WriteAllTextAsync(Path.Combine(seed,"meta-data"),"instance-id: flagship-pod\nlocal-hostname: flagship\n",ct);await File.WriteAllTextAsync(Path.Combine(seed,"vendor-data"),"",ct);await RunAsync(x,["-indev",Disk(src),"-outdev",Disk(dst),"-boot_image","any","replay","-map",Disk(seed),"/nocloud","-map",Disk(grub),"/boot/grub/grub.cfg"],true,ct);}
 static async Task DebianIso(string x,string src,string dst,string data,string work,CancellationToken ct){var ps=Path.Combine(work,"preseed.cfg");await File.WriteAllTextAsync(ps,data,new System.Text.UTF8Encoding(false),ct);var targets=new[]{"/boot/grub/grub.cfg","/EFI/boot/grub.cfg","/isolinux/isolinux.cfg","/isolinux/txt.cfg","/isolinux/gtk.cfg"};var maps=new List<string>();for(var i=0;i<targets.Length;i++){var local=Path.Combine(work,"cfg"+i);await RunAsync(x,["-osirrox","on","-indev",Disk(src),"-extract",targets[i],Disk(local)],false,ct);if(!File.Exists(local)||new FileInfo(local).Length==0)continue;var text=await File.ReadAllTextAsync(local,ct);text=i<2?EditGrubForPreseed(text):EditIsolinuxForPreseed(text);await File.WriteAllTextAsync(local,text,new System.Text.UTF8Encoding(false),ct);maps.AddRange(["-map",Disk(local),targets[i]]);}if(maps.Count==0)throw new InvalidDataException("no Debian boot config found");var args=new List<string>{"-indev",Disk(src),"-outdev",Disk(dst),"-boot_image","any","replay","-map",Disk(ps),"/preseed.cfg"};args.AddRange(maps);await RunAsync(x,args,true,ct);}
 static string Disk(string p)=>ToXorrisoDiskPath(Path.GetFullPath(p),OperatingSystem.IsWindows());
 static async Task<string> RunAsync(string exe,IEnumerable<string> argv,bool fail,CancellationToken ct){var pi=new System.Diagnostics.ProcessStartInfo(exe){UseShellExecute=false,RedirectStandardOutput=true,RedirectStandardError=true,CreateNoWindow=true};foreach(var a in argv)pi.ArgumentList.Add(a);using var p=System.Diagnostics.Process.Start(pi)??throw new InvalidOperationException("could not start xorriso");var so=p.StandardOutput.ReadToEndAsync();var se=p.StandardError.ReadToEndAsync();using var registration=ct.Register(()=>{try{if(!p.HasExited)p.Kill(entireProcessTree:true);}catch{}});await p.WaitForExitAsync();var o=(await so)+"\n"+(await se);ct.ThrowIfCancellationRequested();if(o.Length>32768)o=o[^32768..];if(fail&&p.ExitCode!=0)throw new InvalidOperationException("xorriso failed ("+p.ExitCode+"): "+o);return o;}}