// Webapp half of the shared canonical-bytes contract. Loads THE single
// authoritative fixture (test-vectors/canonical-bytes.json, generated by
// tools/test-vectors.ts) and asserts the webapp's REAL exported canonical
// functions reproduce the recorded bytes for every purpose the webapp
// implements. This is deliberately NOT a transcribed copy of the byte layout
// (that anti-pattern lets a webapp encoder drift while its own test stays
// green) — it pins the webapp encoder to the same source the TS, Swift, and
// Kotlin tests pin to, so a divergence surfaces here instead of as a live
// "signed-by-IRK but the box/.com rejects" failure.
import { describe, expect, it } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { canonicalInstallBlob } from "../public/webapp/lib/buildDraft.js";
import { canonicalSetFrontPageBytes } from "../public/webapp/lib/frontPage.js";
import { canonicalPowerOffBytes } from "../public/webapp/lib/lockAndPower.js";
import { canonicalJournalBytes } from "../public/webapp/lib/journal.js";
import { canonicalPushRevoke } from "../public/webapp/lib/push.js";
import { canonicalRevokeBytes } from "../public/webapp/lib/revokeServer.js";
import { canonicalRePairInitiateBytes } from "../public/webapp/lib/replaceDeviceCeremony.js";

const PATH = resolve(__dirname, "..", "..", "..", "test-vectors", "canonical-bytes.json");

interface Vector {
  name: string;
  signedBy: string;
  input: Record<string, unknown>;
  clients: string[];
  signatureHex: string;
  canonicalHex: string;
}
interface File {
  metadata: Record<string, unknown>;
  vectors: Vector[];
}

function hexToBytes(h: string): Uint8Array {
  const out = new Uint8Array(h.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16);
  return out;
}
function bytesToHex(b: Uint8Array): string {
  let s = "";
  for (const x of b) s += x.toString(16).padStart(2, "0");
  return s;
}

// Map a recorded vector's `input` to the webapp canonical function and return
// its bytes. Only the purposes the webapp actually implements are wired; every
// other purpose is intentionally skipped-with-note below.
const WEBAPP_ENCODERS: Record<string, (i: Record<string, unknown>) => Uint8Array> = {
  revoke: (i) =>
    canonicalRevokeBytes({
      userId: i.userId as string,
      revokedServerId: i.revokedServerId as string,
      reason: i.reason as string,
      issuedAt: i.issuedAt as number,
    }),
  "install-blob": (i) =>
    canonicalInstallBlob({
      version: i.version as number,
      serverDomain: i.serverDomain as string,
      username: i.username as string,
      serverName: i.serverName as string,
      phoneDelegatedPubKey: hexToBytes(i.phoneDelegatedPubKey as string),
      registrationUrl: i.registrationUrl as string,
      authCode: {
        serial: i.authCodeSerial as string,
        userPubKey: hexToBytes(i.authCodeUserPubKey as string),
      },
      authCodeUserSignature: hexToBytes(i.authCodeUserSignature as string),
      installerGitRef: i.installerGitRef as string,
      rckPubKey: hexToBytes(i.rckPubKey as string),
      bootUnlockMode: i.bootUnlockMode as string | undefined,
      diskEncryption: i.diskEncryption as string | undefined,
    }),
  "order-set-front-page": (i) =>
    canonicalSetFrontPageBytes({
      serverId: i.serverId as string,
      label: i.label as string,
      issuedAt: i.issuedAt as number,
    }),
  "order-power-off-off": (i) =>
    canonicalPowerOffBytes({
      serverId: i.serverId as string,
      mode: i.mode as string,
      issuedAt: i.issuedAt as number,
    }),
  "order-power-off-restart": (i) =>
    canonicalPowerOffBytes({
      serverId: i.serverId as string,
      mode: i.mode as string,
      issuedAt: i.issuedAt as number,
    }),
  "journal-read": (i) =>
    canonicalJournalBytes({
      serverId: i.serverId as string,
      unit: i.unit as string,
      lines: i.lines as number,
      issuedAt: i.issuedAt as number,
    }),
  "push-token-revoke": (i) =>
    canonicalPushRevoke({ tokenId: i.tokenId as string, issuedAt: i.issuedAt as number }),
  "re-pair-initiate": (i) =>
    canonicalRePairInitiateBytes({
      username: i.username as string,
      newIrkPubHex: i.newIrkPub as string,
      oldIrkPubHex: i.oldIrkPub as string,
      issuedAt: i.issuedAt as number,
    }),
};

describe("webapp canonical-bytes — shared-fixture parity", () => {
  if (!existsSync(PATH)) {
    it("vectors file MUST exist — run `npx tsx tools/test-vectors.ts`", () => {
      throw new Error(`missing ${PATH}`);
    });
    return;
  }

  const file = JSON.parse(readFileSync(PATH, "utf8")) as File;

  // Sanity: every vector tagged for the webapp has a wired encoder here, and
  // every wired encoder corresponds to a real vector — so neither side drifts
  // silently (a webapp-tagged vector with no encoder, or vice-versa, fails).
  it("webapp-tagged vectors and wired encoders are in lockstep", () => {
    const tagged = file.vectors.filter((v) => v.clients.includes("webapp")).map((v) => v.name).sort();
    const wired = Object.keys(WEBAPP_ENCODERS).sort();
    expect(wired).toEqual(tagged);
  });

  for (const v of file.vectors) {
    if (!v.clients.includes("webapp")) {
      it.skip(`vector "${v.name}" — not implemented in the webapp (by design)`, () => {});
      continue;
    }
    it(`vector "${v.name}" — webapp encoder matches the shared canonicalHex`, () => {
      const enc = WEBAPP_ENCODERS[v.name];
      expect(enc, `no webapp encoder wired for ${v.name}`).toBeDefined();
      const got = bytesToHex(enc!(v.input));
      expect(got).toBe(v.canonicalHex);
    });
  }
});
