/**
 * Source of apps/desktop-shared/golden/alpine-trailer-vectors.json — the
 * contract the three desktop Alpine Quick serializers (Swift, Python, C#)
 * build trailers against. Each vector is a recipe as the desktop app receives
 * it plus the exact trailer JSON and trailer bytes @flagship/iso-personalizer
 * produces for it; the desktop tests load the file, so a desktop serializer
 * that drops or reorders a signed field fails there, and a TS-side change
 * fails here until the file is regenerated:
 *
 *   UPDATE_ALPINE_TRAILER_GOLDEN=1 npx vitest run packages/installer-apkovl/tests/alpineTrailerGolden.test.ts
 */
import { describe, expect, it } from "vitest";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  deriveIRK,
  ed,
  signAuthCode,
  signInstallBlob,
  type AuthCode,
  type InstallBlob,
} from "@flagship/protocol";
import { buildTrailer, installBlobToJson } from "@flagship/iso-personalizer";

const GOLDEN = join(__dirname, "..", "..", "..", "apps", "desktop-shared", "golden", "alpine-trailer-vectors.json");
const irk = deriveIRK({ seed: new Uint8Array(32).fill(11) });
const hex = (b: Uint8Array) => Buffer.from(b).toString("hex");
const key = (fill: number) => ed.getPublicKey(new Uint8Array(32).fill(fill));

function blob(opts: { adminRoot?: boolean; bootUnlockMode?: "auto" | "approve"; diskEncryption?: "luks" | "none" }): InstallBlob {
  const code: AuthCode = {
    version: 1,
    serial: "01HXAFGOLDEN0001",
    username: "bright-maple",
    serverName: "home",
    serverDomain: "home.bright-maple.flagship.services",
    delegatedPubKey: key(3),
    userPubKey: irk.publicKey,
    issuedAt: 1_790_000_000_000,
    expiresAt: 1_790_000_000_000 + 3_600_000,
    ...(opts.adminRoot ? { adminRootPubKey: key(5) } : {}),
  };
  return {
    version: 2,
    serverDomain: code.serverDomain,
    username: code.username,
    serverName: code.serverName,
    phoneDelegatedPubKey: code.delegatedPubKey,
    registrationUrl: "https://flagship.services/api/server/register",
    authCode: code,
    authCodeUserSignature: signAuthCode(code, irk),
    installerGitRef: "main",
    rckPubKey: key(9),
    ...(opts.bootUnlockMode ? { bootUnlockMode: opts.bootUnlockMode } : {}),
    ...(opts.diskEncryption ? { diskEncryption: opts.diskEncryption } : {}),
  };
}

function upperHex(o: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(o)) {
    if (typeof v === "string" && /^[0-9a-f]{64,}$/.test(v)) out[k] = v.toUpperCase();
    else if (v && typeof v === "object") out[k] = upperHex(v as Record<string, unknown>);
    else out[k] = v;
  }
  return out;
}

function vector(name: string, b: InstallBlob, recipeHexCase: "lower" | "upper" = "lower") {
  const sig = signInstallBlob(b, irk);
  const flat = { ...(installBlobToJson(b) as unknown as Record<string, unknown>), blobSignatureHex: hex(sig) };
  const trailer = buildTrailer(b, irk).bytes;
  return {
    name,
    recipe: recipeHexCase === "upper" ? upperHex(flat) : flat,
    trailerJson: JSON.stringify(installBlobToJson(b)),
    trailerHex: hex(trailer),
  };
}

function build() {
  return {
    description:
      "Alpine Quick trailer contract (generated by packages/installer-apkovl/tests/alpineTrailerGolden.test.ts). " +
      "For each recipe, a desktop serializer must emit exactly trailerJson and trailerHex.",
    vectors: [
      vector("minimal", blob({})),
      vector("boot-unlock-approve", blob({ bootUnlockMode: "approve" })),
      vector("disk-encryption-none", blob({ diskEncryption: "none" })),
      vector("every-signed-field", blob({ adminRoot: true, bootUnlockMode: "auto", diskEncryption: "luks" })),
      vector("every-signed-field-uppercase-hex-input", blob({ adminRoot: true, bootUnlockMode: "approve", diskEncryption: "none" }), "upper"),
    ],
  };
}

describe("alpine-trailer-vectors.json", () => {
  it("matches what @flagship/iso-personalizer builds", () => {
    const want = JSON.stringify(build(), null, 2) + "\n";
    if (process.env.UPDATE_ALPINE_TRAILER_GOLDEN === "1") writeFileSync(GOLDEN, want);
    expect(readFileSync(GOLDEN, "utf8")).toBe(want);
  });
});
