// Android half of the shared canonical-bytes contract — mirror of the iOS
// CanonicalBytesVectorsTests + the TS/webapp tests. Loads THE single
// authoritative fixture, test-vectors/canonical-bytes.json (generated by
// tools/test-vectors.ts), FROM DISK at runtime — never transcribed into Kotlin
// literals (same pattern as MaintainersConformanceTest). For every purpose the
// Kotlin client implements it:
//   1. recomputes the canonical bytes via the REAL Kotlin canonical function
//      and asserts byte-equality with the recorded canonicalHex, and
//   2. verifies the recorded Ed25519 signature under the recorded signer pubkey.
// A drift between this client and the source surfaces HERE, not as a live
// "phone signs, .com/box rejects" failure. Purposes Kotlin doesn't implement
// are skipped-with-note (counted, not silently dropped).

package com.flagshipserver.app.core

import com.google.crypto.tink.subtle.Ed25519Verify
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.longOrNull
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Test
import java.io.File

class CanonicalBytesVectorsTest {

    private val json = Json { ignoreUnknownKeys = true }

    // ----- locate the shared fixture on disk (walk up from the JVM unit-test
    // working dir, which is apps/mobile/android/app) -----
    private fun vectorsFile(): File {
        val rel = "test-vectors/canonical-bytes.json"
        val candidates = ArrayList<File>()
        System.getProperty("user.dir")?.let { candidates.add(File(it)) }
        try {
            val loc = javaClass.protectionDomain?.codeSource?.location
            if (loc != null) candidates.add(File(loc.toURI()))
        } catch (_: Throwable) {
            // user.dir walk is the primary path
        }
        for (start in candidates) {
            var dir: File? = start.absoluteFile
            var hops = 0
            while (dir != null && hops < 12) {
                val f = File(dir, rel)
                if (f.isFile) return f
                dir = dir.parentFile
                hops += 1
            }
        }
        fail("could not locate $rel from " + candidates.joinToString { it.absolutePath })
        error("unreachable")
    }

    // ----- JSON helpers (lenient tree decoding) -----
    private fun JsonObject.str(key: String): String = (this[key] as JsonPrimitive).content
    private fun JsonObject.strOrNull(key: String): String? {
        val v = this[key] ?: return null
        if (v is JsonNull) return null
        return (v as JsonPrimitive).contentOrNull
    }
    private fun JsonObject.long(key: String): Long =
        (this[key] as JsonPrimitive).longOrNull ?: error("field $key not a long")
    private fun JsonObject.strList(key: String): List<String> {
        val a = this[key] as? JsonArray ?: return emptyList()
        return a.map { (it as JsonPrimitive).content }
    }

    private fun hex(b: ByteArray): String = HexUtil.encode(b)
    private fun unhex(h: String): ByteArray = HexUtil.decode(h) ?: error("bad hex: $h")

    private fun verifies(sig: ByteArray, bytes: ByteArray, pub: ByteArray): Boolean = try {
        Ed25519Verify(pub).verify(sig, bytes); true
    } catch (_: Throwable) {
        false
    }

    /** The purposes the Kotlin client implements → recompute their canonical
     *  bytes from the recorded `input`. Anything not in this map is skipped. */
    private val encoders: Map<String, (JsonObject) -> ByteArray> = mapOf(
        "revoke" to { i ->
            ServerRevocationClaim.canonicalBytes(
                i.str("userId"), i.str("revokedServerId"), i.str("reason"), i.long("issuedAt"),
            )
        },
        "auth-code" to { i ->
            AuthCode(
                version = 1,
                serial = i.str("serial"),
                username = i.str("username"),
                serverName = i.str("serverName"),
                serverDomain = i.str("serverDomain"),
                delegatedPubKey = unhex(i.str("delegatedPubKey")),
                userPubKey = unhex(i.str("userPubKey")),
                issuedAt = i.long("issuedAt"),
                expiresAt = i.long("expiresAt"),
            ).canonicalBytes()
        },
        "install-blob" to { i ->
            InstallBlob(
                version = i.long("version").toInt(),
                serverDomain = i.str("serverDomain"),
                username = i.str("username"),
                serverName = i.str("serverName"),
                phoneDelegatedPubKey = unhex(i.str("phoneDelegatedPubKey")),
                registrationUrl = i.str("registrationUrl"),
                authCode = AuthCode(
                    version = 1,
                    serial = i.str("authCodeSerial"),
                    username = i.str("username"),
                    serverName = i.str("serverName"),
                    serverDomain = i.str("serverDomain"),
                    delegatedPubKey = ByteArray(0),
                    userPubKey = unhex(i.str("authCodeUserPubKey")),
                    issuedAt = 0,
                    expiresAt = 0,
                ),
                authCodeUserSignature = unhex(i.str("authCodeUserSignature")),
                installerGitRef = i.str("installerGitRef"),
                rckPubKey = unhex(i.str("rckPubKey")),
                bootUnlockMode = i.strOrNull("bootUnlockMode"),
                diskEncryption = i.strOrNull("diskEncryption"),
            ).canonicalBytes()
        },
        "order-set-front-page" to { i ->
            SetFrontPageOrder.canonicalBytes(i.str("serverId"), i.str("label"), i.long("issuedAt"))
        },
        "order-power-off-off" to { i ->
            PowerOffOrder.canonicalBytes(i.str("serverId"), powerMode(i.str("mode")), i.long("issuedAt"))
        },
        "order-power-off-restart" to { i ->
            PowerOffOrder.canonicalBytes(i.str("serverId"), powerMode(i.str("mode")), i.long("issuedAt"))
        },
        "journal-read" to { i ->
            JournalRequest.canonicalBytes(i.str("serverId"), i.str("unit"), i.long("lines"), i.long("issuedAt"))
        },
        "watch-delegate-key" to { i ->
            WatchDelegateKey.canonicalBytes(
                i.str("grantId"), i.str("username"), i.str("delegatePubKey"),
                i.strList("scopes"), i.long("issuedAt"), i.long("expiresAt"),
            )
        },
        "device-capability-grant" to { i ->
            DeviceCapabilityGrant.canonicalBytes(
                i.str("grantId"), i.str("username"), i.str("deviceLabel"), i.str("devicePubKey"),
                i.strList("scopes"), i.long("issuedAt"), i.long("expiresAt"),
            )
        },
        "push-token-revoke" to { i ->
            PushTokenRevoke.canonicalBytes(i.str("tokenId"), i.long("issuedAt"))
        },
        "re-pair-initiate" to { i ->
            RePairInitiateClaim.canonicalBytes(
                i.str("username"), i.str("newIrkPub"), i.str("oldIrkPub"), i.long("issuedAt"),
            )
        },
        "daemon-status" to { i -> daemonBytes(i) },
        "daemon-status-liveness" to { i -> daemonBytes(i) },
    )

    private fun powerMode(wire: String): PowerMode =
        PowerMode.values().firstOrNull { it.wire == wire } ?: error("bad power mode $wire")

    private fun daemonBytes(i: JsonObject): ByteArray =
        DaemonStatusReport.canonicalBytes(
            DaemonStatusReport.Report(
                serverDomain = i.str("serverDomain"),
                certSha256 = i.strOrNull("certSha256"),
                certValidUntil = (i["certValidUntil"] as? JsonPrimitive)?.longOrNull,
                certIssuer = i.strOrNull("certIssuer"),
                appsServed = i.strList("appsServed"),
                nonce = i.str("nonce"),
                issuedAt = i.long("issuedAt"),
            ),
        )

    private fun load(): Pair<JsonObject, List<JsonObject>> {
        val root = json.parseToJsonElement(vectorsFile().readText()).jsonObject
        val vectors = root["vectors"]!!.jsonArray.map { it.jsonObject }
        return root["metadata"]!!.jsonObject to vectors
    }

    private fun pubFor(meta: JsonObject, signedBy: String): ByteArray = when (signedBy) {
        "irk" -> unhex(meta.str("irkPubHex"))
        "old-irk" -> unhex(meta.str("oldIrkPubHex"))
        "bak" -> unhex(meta.str("bakPubHex"))
        "stk" -> unhex(meta.str("stkPubHex"))
        "rck" -> unhex(meta.str("rckPubHex"))
        "identity" -> unhex(meta.str("identityPubHex"))
        else -> ByteArray(0)
    }

    @Test fun everyKotlinImplementedVectorMatchesTheSharedFixture() {
        val (meta, vectors) = load()
        val byName = vectors.associateBy { it.str("name") }

        // Every wired encoder must correspond to a real vector in the file (so a
        // renamed/removed vector can't leave a dead encoder asserting nothing).
        for (name in encoders.keys) {
            assertTrue("wired encoder '$name' has no matching vector in the fixture", byName.containsKey(name))
        }

        var asserted = 0
        var skipped = 0
        for (v in vectors) {
            val name = v.str("name")
            val enc = encoders[name]
            if (enc == null) {
                skipped += 1
                continue
            }
            val input = v["input"]!!.jsonObject
            val got = hex(enc(input))
            assertEquals("canonical bytes drift for $name", v.str("canonicalHex"), got)

            val signedBy = v.str("signedBy")
            if (signedBy != "none") {
                val sig = unhex(v.str("signatureHex"))
                val pub = pubFor(meta, signedBy)
                assertTrue("signature for $name does not verify under $signedBy pub", verifies(sig, enc(input), pub))
            }
            asserted += 1
        }
        // Lock in the coverage so a regression that silently stops asserting a
        // purpose (e.g. an encoder map entry deleted) trips this count.
        assertEquals("expected to assert all wired purposes", encoders.size, asserted)
        assertTrue("expected some purposes to be skipped-by-design", skipped > 0)
    }
}
