import XCTest
@testable import FlagshipBurnerCore

/// Golden-vector tests. The recipe below was produced by the real
/// @flagship/protocol `signInstallBlob` (IRK seed 7, expiry 2099). If the
/// Swift canonical-byte layout or Ed25519 verify drifts from the TypeScript,
/// `load` stops accepting it — that's the regression alarm.
final class RecipeTests: XCTestCase {
    // Generated by packages/protocol signInstallBlob — do not hand-edit.
    static let goldenJSON = """
    {
      "version": 2,
      "serverDomain": "home.golden.flagship.services",
      "username": "golden",
      "serverName": "home",
      "phoneDelegatedPubKey": "1398f62c6d1a457c51ba6a4b5f3dbd2f69fca93216218dc8997e416bd17d93ca",
      "registrationUrl": "https://flagshipserver.com/api/server/register",
      "authCode": {
        "version": 1,
        "serial": "01GOLDENTEST",
        "username": "golden",
        "serverName": "home",
        "serverDomain": "home.golden.flagship.services",
        "delegatedPubKey": "1398f62c6d1a457c51ba6a4b5f3dbd2f69fca93216218dc8997e416bd17d93ca",
        "userPubKey": "ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c",
        "issuedAt": 4070908800000,
        "expiresAt": 4102444800000
      },
      "authCodeUserSignature": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "installerGitRef": "main",
      "rckPubKey": "fd1724385aa0c75b64fb78cd602fa1d991fdebf76b13c58ed702eac835e9f618",
      "blobSignatureHex": "cf239ce92c72081578f5f3c781cf6de127472485eee3ce2b7a748f8057d122bce3690ceed82737892f2f5bf9c45d39ee7c50ed36b46a2b52ef58b9c4b3823505"
    }
    """

    private func data(_ s: String) -> Data { Data(s.utf8) }

    func testAcceptsGoldenRecipe() throws {
        let r = try RecipeLoader.load(data: data(Self.goldenJSON))
        XCTAssertEqual(r.serverDomain, "home.golden.flagship.services")
        XCTAssertEqual(r.username, "golden")
        XCTAssertEqual(r.serverName, "home")
        XCTAssertEqual(r.authCode.serial, "01GOLDENTEST")
    }

    func testRejectsTamperedSignature() {
        let bad = Self.goldenJSON.replacingOccurrences(of: "cf239ce9", with: "ffffffff")
        XCTAssertThrowsError(try RecipeLoader.load(data: data(bad))) { err in
            XCTAssertEqual(err as? RecipeError, .badSignature)
        }
    }

    func testRejectsTamperedField() {
        // Flip the server domain — canonical bytes change, signature must fail.
        let bad = Self.goldenJSON.replacingOccurrences(of: "home.golden.flagship.services",
                                                       with: "home.evil.flagship.services")
        XCTAssertThrowsError(try RecipeLoader.load(data: data(bad))) { err in
            XCTAssertEqual(err as? RecipeError, .badSignature)
        }
    }

    func testRejectsExpired() {
        // Evaluate "now" past the 2099 expiry.
        let future = Date(timeIntervalSince1970: 4_200_000_000)
        XCTAssertThrowsError(try RecipeLoader.load(data: data(Self.goldenJSON), now: future)) { err in
            guard case .expired = (err as? RecipeError) else {
                return XCTFail("expected .expired, got \(err)")
            }
        }
    }

    func testRejectsWrongVersion() {
        let v1 = Self.goldenJSON.replacingOccurrences(of: "\"version\": 2", with: "\"version\": 1")
        XCTAssertThrowsError(try RecipeLoader.load(data: data(v1))) { err in
            XCTAssertEqual(err as? RecipeError, .wrongVersion(1))
        }
    }

    func testHexRoundTrip() {
        XCTAssertEqual(Data(hexString: "00ff10")?.hexString, "00ff10")
        XCTAssertNil(Data(hexString: "xyz"))
        XCTAssertNil(Data(hexString: "abc"))  // odd length
    }
}
