import XCTest
@testable import FlagshipBurnerCore

/// Golden-vector tests. The recipe below was produced by the real
/// @flagship/protocol `signInstallBlob` (IRK seed 7, expiry 2099). If the
/// Swift canonical-byte layout or Ed25519 verify drifts from the TypeScript,
/// `load` stops accepting it — that's the regression alarm.
final class RecipeTests: XCTestCase {
    // Generated by packages/protocol signInstallBlob — do not hand-edit.
    static let goldenJSON = """
    {
      "version": 2,
      "serverDomain": "home.golden.flagship.services",
      "username": "golden",
      "serverName": "home",
      "phoneDelegatedPubKey": "1398f62c6d1a457c51ba6a4b5f3dbd2f69fca93216218dc8997e416bd17d93ca",
      "registrationUrl": "https://flagshipserver.com/api/server/register",
      "authCode": {
        "version": 1,
        "serial": "01GOLDENTEST",
        "username": "golden",
        "serverName": "home",
        "serverDomain": "home.golden.flagship.services",
        "delegatedPubKey": "1398f62c6d1a457c51ba6a4b5f3dbd2f69fca93216218dc8997e416bd17d93ca",
        "userPubKey": "ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c",
        "issuedAt": 4070908800000,
        "expiresAt": 4102444800000
      },
      "authCodeUserSignature": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "installerGitRef": "main",
      "rckPubKey": "fd1724385aa0c75b64fb78cd602fa1d991fdebf76b13c58ed702eac835e9f618",
      "blobSignatureHex": "cf239ce92c72081578f5f3c781cf6de127472485eee3ce2b7a748f8057d122bce3690ceed82737892f2f5bf9c45d39ee7c50ed36b46a2b52ef58b9c4b3823505"
    }
    """

    private func data(_ s: String) -> Data { Data(s.utf8) }

    /// .com and the website hand out the issued envelope { blob, blobSignature };
    /// the burner must accept it, not only the flattened form.
    func testAcceptsIssuedEnvelopeForm() throws {
        var blob = try JSONSerialization.jsonObject(with: data(Self.goldenJSON)) as! [String: Any]
        let sig = blob.removeValue(forKey: "blobSignatureHex") as! String
        let envelope: [String: Any] = ["blob": blob, "blobSignature": sig]
        let r = try RecipeLoader.load(data: try JSONSerialization.data(withJSONObject: envelope))
        XCTAssertEqual(r.serverDomain, "home.golden.flagship.services")
        XCTAssertEqual(r.authCode.serial, "01GOLDENTEST")
    }

    /// Create-time pairing: the recipe's UNSIGNED top-level `pairingKeyPrivHex`
    /// sibling (beside `blob`/`blobSignature`) must survive the envelope flatten
    /// so it lands in the on-disk install-blob.json the daemon reads.
    func testEnvelopeFlattenCarriesPairingKeySibling() throws {
        var blob = try JSONSerialization.jsonObject(with: data(Self.goldenJSON)) as! [String: Any]
        let sig = blob.removeValue(forKey: "blobSignatureHex") as! String
        let pairing = String(repeating: "ab", count: 32)
        let envelope: [String: Any] = ["blob": blob, "blobSignature": sig, "pairingKeyPrivHex": pairing]
        let flat = try JSONSerialization.jsonObject(
            with: RecipeLoader.normalizeEnvelope(try JSONSerialization.data(withJSONObject: envelope))
        ) as! [String: Any]
        XCTAssertEqual(flat["pairingKeyPrivHex"] as? String, pairing)
        XCTAssertEqual(flat["serverDomain"] as? String, "home.golden.flagship.services")
        // A recipe WITHOUT the sibling must not invent one (byte-identical path).
        let plain: [String: Any] = ["blob": blob, "blobSignature": sig]
        let flatNoPair = try JSONSerialization.jsonObject(
            with: RecipeLoader.normalizeEnvelope(try JSONSerialization.data(withJSONObject: plain))
        ) as! [String: Any]
        XCTAssertNil(flatNoPair["pairingKeyPrivHex"])
    }

    func testAcceptsGoldenRecipe() throws {
        let r = try RecipeLoader.load(data: data(Self.goldenJSON))
        XCTAssertEqual(r.serverDomain, "home.golden.flagship.services")
        XCTAssertEqual(r.username, "golden")
        XCTAssertEqual(r.serverName, "home")
        XCTAssertEqual(r.authCode.serial, "01GOLDENTEST")
    }

    func testRejectsTamperedSignature() {
        let bad = Self.goldenJSON.replacingOccurrences(of: "cf239ce9", with: "ffffffff")
        XCTAssertThrowsError(try RecipeLoader.load(data: data(bad))) { err in
            XCTAssertEqual(err as? RecipeError, .badSignature)
        }
    }

    func testRejectsTamperedField() {
        // Flip the server domain — canonical bytes change, signature must fail.
        let bad = Self.goldenJSON.replacingOccurrences(of: "home.golden.flagship.services",
                                                       with: "home.evil.flagship.services")
        XCTAssertThrowsError(try RecipeLoader.load(data: data(bad))) { err in
            XCTAssertEqual(err as? RecipeError, .badSignature)
        }
    }

    func testRejectsExpired() {
        // Evaluate "now" past the 2099 expiry.
        let future = Date(timeIntervalSince1970: 4_200_000_000)
        XCTAssertThrowsError(try RecipeLoader.load(data: data(Self.goldenJSON), now: future)) { err in
            guard case .expired = (err as? RecipeError) else {
                return XCTFail("expected .expired, got \(err)")
            }
        }
    }

    func testRejectsWrongVersion() {
        let v1 = Self.goldenJSON.replacingOccurrences(of: "\"version\": 2", with: "\"version\": 1")
        XCTAssertThrowsError(try RecipeLoader.load(data: data(v1))) { err in
            XCTAssertEqual(err as? RecipeError, .wrongVersion(1))
        }
    }

    func testHexRoundTrip() {
        XCTAssertEqual(Data(hexString: "00ff10")?.hexString, "00ff10")
        XCTAssertNil(Data(hexString: "xyz"))
        XCTAssertNil(Data(hexString: "abc"))  // odd length
    }

    // Generated by packages/protocol signInstallBlob WITH bootUnlockMode:"approve"
    // (IRK seed 7, expiry 2099). It proves the Swift canonical-byte layout APPENDS
    // bootUnlockMode exactly as @flagship/protocol does — if Swift dropped the
    // field, this real signature would no longer verify. Do not hand-edit.
    static let approveGoldenJSON = #"{"version":2,"serverDomain":"home.demoalice.flagship.services","username":"demoalice","serverName":"home","phoneDelegatedPubKey":"1398f62c6d1a457c51ba6a4b5f3dbd2f69fca93216218dc8997e416bd17d93ca","registrationUrl":"https://flagshipserver.com/api/server/register","authCode":{"version":1,"serial":"01TESTAPPROV","username":"demoalice","serverName":"home","serverDomain":"home.demoalice.flagship.services","delegatedPubKey":"1398f62c6d1a457c51ba6a4b5f3dbd2f69fca93216218dc8997e416bd17d93ca","userPubKey":"ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c","issuedAt":1000,"expiresAt":99999999999999},"authCodeUserSignature":"d696674534e72422b93ae38f52d4ebb6777ccf4c562ed0e346bf059dced2585eb41409cb14dcc6ab3b56442d5af1cbbc1d4fcf060f5fde91b33d8d7b470e9f06","installerGitRef":"main","rckPubKey":"fd1724385aa0c75b64fb78cd602fa1d991fdebf76b13c58ed702eac835e9f618","blobSignatureHex":"f29ad6f68c8f72c99f25b158373689724a9bc67ea8a38abd1dc97f81f5d843a9d948885b23facd65ccf99cc6edc4b7bb814f5085a796fce66251bfad583ce500","bootUnlockMode":"approve"}"#

    func testAcceptsApproveModeRecipe() throws {
        let r = try RecipeLoader.load(data: data(Self.approveGoldenJSON))
        XCTAssertEqual(r.bootUnlockMode, "approve")
        XCTAssertEqual(r.effectiveBootUnlockMode, "approve")
    }

    func testApproveModeIsCovenantBySignature() {
        // Strip bootUnlockMode from a recipe whose signature COMMITTED to it —
        // the canonical bytes change, so verification must fail (a relay/.com
        // cannot downgrade an "approve" server to "auto").
        let downgraded = Self.approveGoldenJSON
            .replacingOccurrences(of: #","bootUnlockMode":"approve""#, with: "")
        XCTAssertThrowsError(try RecipeLoader.load(data: data(downgraded))) { err in
            XCTAssertEqual(err as? RecipeError, .badSignature)
        }
    }

    // A recipe carrying diskEncryption:"none" (the Wi-Fi-only fallback),
    // signed by @flagship/protocol signInstallBlob over the trailing `de=none`.
    // Generated by packages/protocol with fixed seeds (userPubKey 8146…9a3e).
    // If Swift's canonicalBytes dropped or mis-spelled the `de=` append, this
    // valid recipe would be rejected. Do not hand-edit.
    static let diskEncryptionNoneGoldenJSON = #"{"version":2,"serverDomain":"home.denone.flagship.services","username":"denone","serverName":"home","phoneDelegatedPubKey":"c86d01ad8b2fb694b22ff60e3c9d9e7ed90db5604772b74450d40913b9a9cbaf","registrationUrl":"https://flagshipserver.com/api/server/register","authCode":{"version":1,"serial":"01DENONE0001","username":"denone","serverName":"home","serverDomain":"home.denone.flagship.services","delegatedPubKey":"c86d01ad8b2fb694b22ff60e3c9d9e7ed90db5604772b74450d40913b9a9cbaf","userPubKey":"8146640f02493af4fbc54fe33388e75dc2c937ae0b7727cc2b2afb1b75199a3e","issuedAt":1000,"expiresAt":99999999999999},"authCodeUserSignature":"55555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555","installerGitRef":"main","rckPubKey":"ba42458e83ba7926ba8b8f3e9ab9caaf0f1c4918dda8c551084f7aeb1065b74b","diskEncryption":"none","blobSignatureHex":"31da15400225ae17acde21eb50bbe51f0b939754283c231e99c9edf307731d48899f5bf314278a5c58d81b093d550b53fd05c8917cb0b28481cf78f18759d002"}"#

    func testAcceptsDiskEncryptionNoneRecipe() throws {
        let r = try RecipeLoader.load(data: data(Self.diskEncryptionNoneGoldenJSON))
        XCTAssertEqual(r.serverDomain, "home.denone.flagship.services")
        XCTAssertEqual(r.diskEncryption, "none")
        // The burner consumes this: "none" ⇒ skip LUKS.
        XCTAssertFalse(r.encryptsDisk)
    }

    func testDiskEncryptionIsCovenantBySignature() {
        // Flip none→luks: canonical bytes become `de=luks`, so the committed
        // signature must fail — a relay can't downgrade/upgrade the encryption
        // posture a phone signed.
        let tampered = Self.diskEncryptionNoneGoldenJSON
            .replacingOccurrences(of: #""diskEncryption":"none""#, with: #""diskEncryption":"luks""#)
        XCTAssertThrowsError(try RecipeLoader.load(data: data(tampered))) { err in
            XCTAssertEqual(err as? RecipeError, .badSignature)
        }
        // Stripping the field entirely (re-present a "none" recipe as legacy/
        // encrypted) must also fail.
        let stripped = Self.diskEncryptionNoneGoldenJSON
            .replacingOccurrences(of: #","diskEncryption":"none""#, with: "")
        XCTAssertThrowsError(try RecipeLoader.load(data: data(stripped))) { err in
            XCTAssertEqual(err as? RecipeError, .badSignature)
        }
    }

    func testAbsentDiskEncryptionDefaultsToEncrypted() throws {
        // The original golden recipe carries no diskEncryption ⇒ nil ⇒ the box
        // encrypts (encryptsDisk == true). Backward compatibility.
        let r = try RecipeLoader.load(data: data(Self.goldenJSON))
        XCTAssertNil(r.diskEncryption)
        XCTAssertTrue(r.encryptsDisk)
    }

}
