import type { AppManifest } from "@flagship/protocol";

export interface CaddyAppEntry {
  manifest: AppManifest;
  /** Logical app id (used in URLs to the daemon's /apps/:id/identity/decide). */
  serviceId: string;
  /** Container hostname inside the user-network — e.g. `app-habit-tracker.flagship.local`. */
  containerHost: string;
}

export interface CaddyContext {
  /** The user's DNS label — e.g. "harry". */
  username: string;
  /**
   * The server's DNS label — e.g. "home-box". Apps are addressed at
   * `<app>.<server>.<user>.flagship.services` so the user can run
   * multiple servers under the same `<user>` namespace.
   */
  serverName: string;
  /**
   * The data-plane apex these names live under — `flagship.services` in
   * prod, `gym.flagship.services` in the test env (docs/ui-test-gym.md
   * §6.5). Defaults to the prod literal so existing callers are unchanged.
   */
  apex?: string;
  /** Daemon address Caddy can reach. Default 127.0.0.1:9090. */
  daemonAddr?: string;
  /** TLS-cert source. Path to PEM bundle on disk that Caddy reads via `tls`. */
  tls?: { certPath: string; keyPath: string };
}

/**
 * The box's own FQDN — `<server>.<user>.<apex>`, the apex SAN of the
 * per-box cert (model A′) and the zone every canonical service name lives
 * under. `apex` defaults to the prod literal `flagship.services`.
 */
export function serverFqdn(ctx: CaddyContext): string {
  return `${ctx.serverName}.${ctx.username}.${ctx.apex ?? "flagship.services"}`;
}

/**
 * Build the canonical FQDN for one app on this server (model A′):
 * `<app>.<server>.<user>.flagship.services`, covered by the box's own
 * wildcard cert. Hierarchy replaces the retired `--` pin flattening.
 */
export function appFqdn(ctx: CaddyContext, subdomain: string): string {
  return `${subdomain}.${serverFqdn(ctx)}`;
}

/**
 * Build the wildcard Caddy site selector for THIS BOX's zone —
 * e.g. `*.home-box.harry.flagship.services` (model A′). It matches every
 * canonical service name on this box and nothing on a sibling box; the box
 * only ever receives the names the tunnel hub routes to it.
 */
export function serverWildcardSelector(ctx: CaddyContext): string {
  return `*.${serverFqdn(ctx)}`;
}

/**
 * Emit a Caddyfile that:
 * 1. Terminates per-app TLS using the box's own wildcard cert (model A′:
 *    `[<server>.<user>, *.<server>.<user>].flagship.services`, minted by the
 *    box's ACME flow with a box-local key).
 * 2. STRIPS any client-supplied X-Flagship-* headers (defense against header
 *    injection — the platform's identity guarantees rest on this strip).
 * 3. Calls the local daemon's POST /apps/:id/identity/decide to authorize the
 *    request and obtain the X-Flagship-User / Role / Signature headers.
 * 4. Forwards to the app container with the injected headers.
 *
 * The Caddyfile is intentionally readable rather than minimal — operators
 * audit it after a fresh install.
 */
export function renderCaddyfile(ctx: CaddyContext, apps: CaddyAppEntry[]): string {
  const daemon = ctx.daemonAddr ?? "127.0.0.1:9090";
  const tlsBlock = ctx.tls
    ? `\n  tls ${q(ctx.tls.certPath)} ${q(ctx.tls.keyPath)}`
    : "\n  tls internal";

  const lines: string[] = [];
  lines.push("# flagship.app Caddyfile — generated by bootkey-builder.");
  lines.push("# DO NOT EDIT BY HAND. Regenerate with `flagship-bootkey-builder`.");
  lines.push("");
  lines.push("{");
  lines.push("  admin off");
  lines.push("  auto_https off");
  lines.push("  servers {");
  lines.push("    metrics");
  lines.push("  }");
  lines.push("}");
  lines.push("");

  for (const entry of apps) {
    const fqdn = appFqdn(ctx, entry.manifest.network.subdomain);
    const target = entry.containerHost.includes(":")
      ? entry.containerHost
      : `${entry.containerHost}:${entry.manifest.runtime.port}`;
    lines.push(`# ${entry.serviceId} — ${entry.manifest.description ?? entry.manifest.name}`);
    lines.push(`${fqdn} {${tlsBlock}`);
    lines.push("");
    lines.push("  # 2. Strip any client-supplied identity headers — the only valid source");
    lines.push("  # is our own injection step below. Without this, an attacker could pass");
    lines.push("  # `X-Flagship-User: alice` and bypass auth.");
    lines.push("  request_header -X-Flagship-User");
    lines.push("  request_header -X-Flagship-Role");
    lines.push("  request_header -X-Flagship-Signature");
    lines.push("  request_header -X-Flagship-Member");
    lines.push("");
    lines.push("  # 3. Hand the request to the daemon's /identity/decide which returns the");
    lines.push("  # signed identity headers (or a 403 page rendered by the daemon).");
    lines.push(`  forward_auth ${q(daemon)} {`);
    lines.push(`    uri /apps/${entry.serviceId}/identity/decide`);
    lines.push("    copy_headers X-Flagship-User X-Flagship-Role X-Flagship-Signature X-Flagship-Member");
    lines.push("  }");
    lines.push("");
    lines.push("  # 4. App container.");
    lines.push(`  reverse_proxy ${q(target)}`);
    lines.push("}");
    lines.push("");
  }

  // Catch-all for the box apex + unknown names under THIS BOX's zone (both
  // covered by the per-box cert). The box only ever receives the names the
  // tunnel hub routes to it, so this stays local.
  lines.push(`${serverFqdn(ctx)}, ${serverWildcardSelector(ctx)} {${tlsBlock}`);
  lines.push("  respond \"app not found\" 404");
  lines.push("}");

  return lines.join("\n") + "\n";
}

function q(s: string): string {
  return JSON.stringify(s);
}

/**
 * Convenience: a ConfigFile entry suitable for the BuildPlan / rootfs writer.
 */
export function caddyfileConfigFile(
  ctx: CaddyContext,
  apps: CaddyAppEntry[] = [],
): { path: string; content: string; mode: number } {
  return {
    path: "/etc/caddy/Caddyfile",
    content: renderCaddyfile(ctx, apps),
    mode: 0o644,
  };
}
