/**
 * LUKS-unlock-on-boot domain — the box-sealed-key custody + auto-unlock
 * lease envelopes (PutSealedLuksKey, ConsumeUnlockKey, AutoUnlockLease,
 * RevokeAutoUnlockLease).
 *
 * Extracted verbatim from the original monolithic `auth.ts`; tags, field
 * order, and guards are unchanged, so canonical bytes and signatures remain
 * byte-identical.
 */
import { ed } from "./edSync.js";
import { hex, legacyFieldGuard } from "./canonicalBase.js";
import type { Bytes, Keypair, ServerId } from "./types.js";

/**
 * LUKS-unlock-on-boot endpoints (RELAY + box-sealed-lease model).
 *
 * Flow:
 *   1. At install time, the daemon seals the LUKS root key with the
 *      user's BAK pubkey and POSTs `PutSealedLuksKey` to .com (signed
 *      by the server identity key).
 *   2. At boot, the box self-unlocks from a box-sealed lease, or falls
 *      back to the relay (an STK-signed `SecretRequest` the phone
 *      answers with a sealed reply). The unlock key is released to the
 *      box via an IRK-signed `AutoUnlockLease` deposited at .com.
 *   3. Boot stage POSTs `ConsumeUnlockKey` (signed by server identity)
 *      to fetch the lease-released key and atomically clear a one-shot
 *      lease.
 *
 * NOTE: the legacy plaintext `DepositUnlockKey` path (where .com held
 * the unsealed key in a form it could read) has been removed. .com now
 * only ever stores ciphertext it cannot read.
 */
export interface PutSealedLuksKey {
  serverId: ServerId;
  sealedKey: Bytes;
  issuedAt: number;
}

export interface ConsumeUnlockKey {
  serverId: ServerId;
  /** 32-byte nonce; rejected if it matches the previous accepted one. */
  nonce: Bytes;
  issuedAt: number;
}

/**
 * Auto-unlock lease — the unified shape that subsumes both
 * "one-shot reactive deposit" (default per-boot) and "out-and-about
 * long-lived lease" (opt-in toggle).
 *
 * `multiUse=false`: one-shot — the boot stage's first `/consume`
 *   returns the key and `.com` deletes the row. `expiresAt` typically
 *   a few minutes after `issuedAt`.
 *
 * `multiUse=true`: persists across multiple `/consume` calls until
 *   `expiresAt`. Lets a server reboot freely while the lease is
 *   live; once it expires, the next boot waits for a fresh lease
 *   (one-shot or renewed long-lived). `expiresAt` typically days
 *   out, with the user's device renewing while it's online.
 *
 * `leaseId` is a unique identifier (16+ hex chars, generated by the
 * signing device) used as the revoke handle. Multiple long-lived
 * leases can coexist for the same server (e.g., user's phone AND
 * webapp both signed); each is independently revocable.
 *
 * Signed by IRK (any device-class IRK is accepted — phone or webapp;
 * the webapp is a peer device, not a phone-remote).
 */
export interface AutoUnlockLease {
  serverId: ServerId;
  /** Unique handle for this lease (16+ hex chars). */
  leaseId: string;
  /** Wall-clock ms after which the lease is no longer valid. */
  expiresAt: number;
  unlockKey: Bytes;
  /** When true, surviving across multiple consume calls until expiry. */
  multiUse: boolean;
  issuedAt: number;
}

/**
 * Revoke a previously-deposited auto-unlock lease (kill switch from
 * the user's device). The signature must be from the same IRK that
 * signed the lease, but `.com` only stores the IRK pubkey indirectly
 * (via the username record), so we accept any IRK signature for the
 * server's owning user — this matches the trust model: any device of
 * yours can revoke any lease on any of your servers.
 */
export interface RevokeAutoUnlockLease {
  serverId: ServerId;
  leaseId: string;
  issuedAt: number;
}

const TAG_PUT_SEALED_LUKS_KEY = "flagship/put-sealed-luks-key/v1";
const TAG_CONSUME_UNLOCK_KEY = "flagship/consume-unlock-key/v1";
const TAG_AUTO_UNLOCK_LEASE = "flagship/auto-unlock-lease/v1";
const TAG_REVOKE_AUTO_UNLOCK_LEASE = "flagship/revoke-auto-unlock-lease/v1";

function canonicalPutSealedLuksKey(r: PutSealedLuksKey): Bytes {
  return new TextEncoder().encode(
    [TAG_PUT_SEALED_LUKS_KEY, r.serverId, hex(r.sealedKey), r.issuedAt].join("|"),
  );
}

function canonicalConsumeUnlockKey(r: ConsumeUnlockKey): Bytes {
  return new TextEncoder().encode(
    [TAG_CONSUME_UNLOCK_KEY, r.serverId, hex(r.nonce), r.issuedAt].join("|"),
  );
}

function canonicalAutoUnlockLease(r: AutoUnlockLease): Bytes {
  legacyFieldGuard("leaseId", r.leaseId);
  // Field order is part of the canonical-bytes contract; do NOT reorder.
  // multiUse is encoded "1" / "0" rather than the JS string of a boolean
  // because the canonical-bytes layer is language-neutral.
  return new TextEncoder().encode(
    [
      TAG_AUTO_UNLOCK_LEASE,
      r.serverId,
      r.leaseId,
      r.expiresAt,
      hex(r.unlockKey),
      r.multiUse ? "1" : "0",
      r.issuedAt,
    ].join("|"),
  );
}

function canonicalRevokeAutoUnlockLease(r: RevokeAutoUnlockLease): Bytes {
  legacyFieldGuard("leaseId", r.leaseId);
  return new TextEncoder().encode(
    [TAG_REVOKE_AUTO_UNLOCK_LEASE, r.serverId, r.leaseId, r.issuedAt].join("|"),
  );
}

export function signPutSealedLuksKey(r: PutSealedLuksKey, identity: Keypair): Bytes {
  return ed.sign(canonicalPutSealedLuksKey(r), identity.privateKey);
}
export function verifyPutSealedLuksKey(r: PutSealedLuksKey, sig: Bytes, identityPub: Bytes): boolean {
  try {
    return ed.verify(sig, canonicalPutSealedLuksKey(r), identityPub);
  } catch {
    return false;
  }
}

export function signConsumeUnlockKey(r: ConsumeUnlockKey, identity: Keypair): Bytes {
  return ed.sign(canonicalConsumeUnlockKey(r), identity.privateKey);
}
export function verifyConsumeUnlockKey(r: ConsumeUnlockKey, sig: Bytes, identityPub: Bytes): boolean {
  try {
    return ed.verify(sig, canonicalConsumeUnlockKey(r), identityPub);
  } catch {
    return false;
  }
}

export function signAutoUnlockLease(r: AutoUnlockLease, irk: Keypair): Bytes {
  return ed.sign(canonicalAutoUnlockLease(r), irk.privateKey);
}
export function verifyAutoUnlockLease(r: AutoUnlockLease, sig: Bytes, irkPub: Bytes): boolean {
  try {
    return ed.verify(sig, canonicalAutoUnlockLease(r), irkPub);
  } catch {
    return false;
  }
}

export function signRevokeAutoUnlockLease(r: RevokeAutoUnlockLease, irk: Keypair): Bytes {
  return ed.sign(canonicalRevokeAutoUnlockLease(r), irk.privateKey);
}
export function verifyRevokeAutoUnlockLease(
  r: RevokeAutoUnlockLease,
  sig: Bytes,
  irkPub: Bytes,
): boolean {
  try {
    return ed.verify(sig, canonicalRevokeAutoUnlockLease(r), irkPub);
  } catch {
    return false;
  }
}
