// Cross-language canonical-bytes vectors — the TS half of the shared-fixture
// contract. The SINGLE authoritative file is test-vectors/canonical-bytes.json
// (generated by tools/test-vectors.ts). TS, webapp, Swift and Kotlin tests all
// LOAD this same file and assert byte-equality for the purposes each
// implements — so a TS-only canonical-byte change cannot ship green while a
// mirror asserts a stale transcribed copy (the hardest cross-platform bug).
//
// This TS test does two things per vector:
//   1. Re-derives the byte layout from the recorded `input` via the PRODUCTION
//      encoder/sign functions and confirms the recorded signature verifies.
//      Because Ed25519 is deterministic, a production canonical-byte change
//      would change the bytes → the recorded (now stale) signature stops
//      verifying → this fails. That is the drift trip-wire on the TS side.
//   2. Confirms the recorded `canonicalHex` matches the bytes the recorded
//      signature was produced over (signer pubkey verify against canonicalHex),
//      so the bytes the clients pin are exactly the signed bytes.
import { describe, expect, it } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import {
  ed,
  deriveIRK,
  deriveBAK,
  deriveSWK,
  deriveSTK,
  verifyAccountRecovery,
  verifyAdminRootRotation,
  verifyAuthCode,
  verifyDaemonStatusReport,
  verifyDeviceCapabilityGrant,
  verifyInstallBlob,
  verifyInvite,
  verifyInviteAcceptance,
  verifyJournalRequest,
  verifyMembershipMutation,
  verifyMigrationRequest,
  verifyPbAnnounce,
  verifyPbPeerConfirm,
  verifyPbRequestPeers,
  verifyPhoneOrder,
  verifyPushTokenRevoke,
  verifyRebuildRequest,
  verifyRegisterServer,
  verifyRePairInitiate,
  verifyRePairObject,
  verifyRevocation,
  verifyRevokeDeviceCapabilityGrant,
  verifyServerRegister,
  verifySetRoutingTarget,
  verifyTunnelHello,
  verifyWatchDelegateKey,
  type DeviceScope,
} from "../src/index.js";

const PATH = resolve(__dirname, "..", "..", "..", "test-vectors", "canonical-bytes.json");

interface Vector {
  name: string;
  signedBy:
    | "irk"
    | "bak"
    | "stk"
    | "old-irk"
    | "rck"
    | "identity"
    | "admin-root"
    | "none";
  input: Record<string, unknown>;
  clients: string[];
  signatureHex: string;
  canonicalHex: string;
}

interface File {
  metadata: {
    umkSeedHex: string;
    oldUmkSeedHex: string;
    irkPubHex: string;
    oldIrkPubHex: string;
    bakPubHex: string;
    stkPubHex: string;
    rckPubHex: string;
    identityPubHex: string;
    adminRootPubHex: string;
    newAdminRootPubHex: string;
    version: number;
  };
  vectors: Vector[];
}

function hexToBytes(h: string): Uint8Array {
  const out = new Uint8Array(h.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16);
  return out;
}

describe("cross-language canonical-bytes vectors (shared fixture)", () => {
  if (!existsSync(PATH)) {
    it("vectors file MUST exist — run `npx tsx tools/test-vectors.ts`", () => {
      throw new Error(`missing ${PATH}`);
    });
    return;
  }

  const file = JSON.parse(readFileSync(PATH, "utf8")) as File;
  const irkPub = hexToBytes(file.metadata.irkPubHex);
  const oldIrkPub = hexToBytes(file.metadata.oldIrkPubHex);
  const bakPub = hexToBytes(file.metadata.bakPubHex);
  const stkPub = hexToBytes(file.metadata.stkPubHex);
  const rckPub = hexToBytes(file.metadata.rckPubHex);
  const identityPub = hexToBytes(file.metadata.identityPubHex);
  const adminRootPub = hexToBytes(file.metadata.adminRootPubHex);

  const pubFor = (signedBy: Vector["signedBy"]): Uint8Array => {
    switch (signedBy) {
      case "irk":
        return irkPub;
      case "old-irk":
        return oldIrkPub;
      case "bak":
        return bakPub;
      case "stk":
        return stkPub;
      case "rck":
        return rckPub;
      case "identity":
        return identityPub;
      case "admin-root":
        return adminRootPub;
      case "none":
        return new Uint8Array(0);
    }
  };

  // Metadata pubkeys must be reproducible from the recorded seeds (proves the
  // fixture's keys are the deterministic ones every client re-derives).
  it("metadata pubkeys re-derive from the recorded seeds", () => {
    const umk = { seed: hexToBytes(file.metadata.umkSeedHex) };
    expect([...deriveIRK(umk).publicKey]).toEqual([...irkPub]);
    expect([...deriveBAK(umk, "srv-test").publicKey]).toEqual([...bakPub]);
    expect([...deriveSTK(deriveSWK(umk, "srv-test")).publicKey]).toEqual([...stkPub]);
    const oldUmk = { seed: hexToBytes(file.metadata.oldUmkSeedHex) };
    expect([...deriveIRK(oldUmk).publicKey]).toEqual([...oldIrkPub]);
  });

  // Typed PRODUCTION verify for the vectors whose verifier takes a structured
  // input — recomputes the canonical bytes inside the production encoder. If a
  // production encoder drifts, the recorded signature stops verifying here.
  const typedVerify = (v: Vector): boolean | undefined => {
    const sig = hexToBytes(v.signatureHex);
    const i = v.input;
    const fromHex = (k: string) =>
      typeof i[k] === "string" ? hexToBytes(i[k] as string) : new Uint8Array(0);
    switch (v.name) {
      case "rebuild":
        return verifyRebuildRequest(
          {
            userId: i.userId as string,
            newServerId: i.newServerId as string,
            wifiSsid: i.wifiSsid as string,
            wifiPskHash: fromHex("wifiPskHash"),
            shareRatio: i.shareRatio as number,
            issuedAt: i.issuedAt as number,
          },
          sig,
          irkPub,
        );
      case "revoke":
        return verifyRevocation(
          {
            userId: i.userId as string,
            revokedServerId: i.revokedServerId as string,
            reason: i.reason as "lost" | "stolen" | "decommissioned",
            issuedAt: i.issuedAt as number,
          },
          sig,
          irkPub,
        );
      case "membership":
        return verifyMembershipMutation(
          {
            serviceId: i.serviceId as string,
            targetIrkPub: fromHex("targetIrkPub"),
            role: (i.role as string | null) ?? null,
            issuedAt: i.issuedAt as number,
          },
          sig,
          irkPub,
        );
      case "migration":
        return verifyMigrationRequest(
          {
            serviceId: i.serviceId as string,
            fromUser: i.fromUser as string,
            toUser: i.toUser as string,
            mode: i.mode as "cut" | "copy",
            withData: i.withData as boolean,
            issuedAt: i.issuedAt as number,
          },
          sig,
          irkPub,
        );
      case "invite":
        return verifyInvite(
          {
            serviceId: i.serviceId as string,
            role: i.role as string,
            nonce: fromHex("nonce"),
            issuedAt: i.issuedAt as number,
            expiresAt: i.expiresAt as number,
          },
          sig,
          irkPub,
        );
      case "invite-acceptance":
        return verifyInviteAcceptance(
          {
            inviteNonce: fromHex("inviteNonce"),
            accepterIrkPub: fromHex("accepterIrkPub"),
            acceptedAt: i.acceptedAt as number,
          },
          sig,
          irkPub,
        );
      case "tunnel-hello":
        return verifyTunnelHelloLocal(i, sig, bakPub);
      case "register-server":
        return verifyRegisterServer(
          {
            userId: i.userId as string,
            serverId: i.serverId as string,
            stkPub: fromHex("stkPub"),
            issuedAt: i.issuedAt as number,
          },
          sig,
          irkPub,
        );
      case "account-recovery":
        return verifyAccountRecovery(
          {
            userId: i.userId as string,
            newPushTokenHash: fromHex("newPushTokenHash"),
            platform: i.platform as "apns" | "fcm",
            issuedAt: i.issuedAt as number,
          },
          sig,
          irkPub,
        );
      case "pb-announce":
        return verifyPbAnnounce(
          {
            serverId: i.serverId as string,
            pledgedBytes: i.pledgedBytes as number,
            shareRatio: i.shareRatio as number,
            maxShardSize: i.maxShardSize as number,
            region: i.region as string | undefined,
            tunnelEndpoint: i.tunnelEndpoint as string,
            issuedAt: i.issuedAt as number,
          },
          sig,
          stkPub,
        );
      case "pb-request-peers":
        return verifyPbRequestPeers(
          {
            requesterServerId: i.requesterServerId as string,
            n: i.n as number,
            shardSizeBytes: i.shardSizeBytes as number,
            durabilityHint: i.durabilityHint as "high" | "best-effort",
            issuedAt: i.issuedAt as number,
          },
          sig,
          stkPub,
        );
      case "pb-peer-confirm":
        return verifyPbPeerConfirm(
          {
            peerServerId: i.peerServerId as string,
            requesterServerId: i.requesterServerId as string,
            shardId: i.shardId as string,
            issuedAt: i.issuedAt as number,
          },
          sig,
          stkPub,
        );
      case "auth-code":
        return verifyAuthCode(
          {
            version: 1,
            serial: i.serial as string,
            username: i.username as string,
            serverName: i.serverName as string,
            serverDomain: i.serverDomain as string,
            delegatedPubKey: fromHex("delegatedPubKey"),
            userPubKey: fromHex("userPubKey"),
            issuedAt: i.issuedAt as number,
            expiresAt: i.expiresAt as number,
          },
          sig,
          irkPub,
        );
      case "install-blob":
        return verifyInstallBlob(
          {
            version: 2,
            serverDomain: i.serverDomain as string,
            username: i.username as string,
            serverName: i.serverName as string,
            phoneDelegatedPubKey: fromHex("phoneDelegatedPubKey"),
            registrationUrl: i.registrationUrl as string,
            authCode: {
              version: 1,
              serial: i.authCodeSerial as string,
              username: i.username as string,
              serverName: i.serverName as string,
              serverDomain: i.serverDomain as string,
              delegatedPubKey: new Uint8Array(0),
              userPubKey: fromHex("authCodeUserPubKey"),
              issuedAt: 0,
              expiresAt: 0,
            },
            authCodeUserSignature: fromHex("authCodeUserSignature"),
            installerGitRef: i.installerGitRef as string,
            rckPubKey: fromHex("rckPubKey"),
            bootUnlockMode: i.bootUnlockMode as "auto" | "approve" | undefined,
            diskEncryption: i.diskEncryption as "luks" | "none" | undefined,
          },
          sig,
          irkPub,
        );
      case "server-register":
        return verifyServerRegister(
          {
            authCode: {
              version: 1,
              serial: i.authCodeSerial as string,
              username: "harry",
              serverName: "home",
              serverDomain: i.authCodeServerDomain as string,
              delegatedPubKey: new Uint8Array(0),
              userPubKey: new Uint8Array(0),
              issuedAt: 0,
              expiresAt: 0,
            },
            authCodeUserSignature: new Uint8Array(0),
            serverIdentityPubKey: fromHex("serverIdentityPubKey"),
            issuedAt: i.issuedAt as number,
            nonce: fromHex("nonce"),
          },
          sig,
          identityPub,
        );
      case "rck-set-target":
        return verifySetRoutingTarget(
          {
            subdomain: i.subdomain as string,
            newTargetIdentityPubKey: fromHex("newTargetIdentityPubKey"),
            issuedAt: i.issuedAt as number,
            nonce: fromHex("nonce"),
          },
          sig,
          rckPub,
        );
      case "order-set-front-page":
        return verifyPhoneOrder(
          {
            type: "set-front-page",
            serverId: i.serverId as string,
            label: i.label as string,
            issuedAt: i.issuedAt as number,
          },
          sig,
          irkPub,
        );
      case "order-power-off-off":
      case "order-power-off-restart":
        return verifyPhoneOrder(
          {
            type: "power-off",
            serverId: i.serverId as string,
            mode: i.mode as "off" | "restart",
            issuedAt: i.issuedAt as number,
          },
          sig,
          irkPub,
        );
      case "journal-read":
        return verifyJournalRequest(
          {
            serverId: i.serverId as string,
            unit: i.unit as string,
            lines: i.lines as number,
            issuedAt: i.issuedAt as number,
          },
          sig,
          irkPub,
        );
      case "watch-delegate-key":
        return verifyWatchDelegateKey(
          {
            grantId: i.grantId as string,
            username: i.username as string,
            delegatePubKey: fromHex("delegatePubKey"),
            scopes: i.scopes as ("boot-approval")[],
            issuedAt: i.issuedAt as number,
            expiresAt: i.expiresAt as number,
          },
          sig,
          irkPub,
        );
      case "device-capability-grant":
        return verifyDeviceCapabilityGrant(
          {
            grantId: i.grantId as string,
            username: i.username as string,
            deviceLabel: i.deviceLabel as string,
            devicePubKey: fromHex("devicePubKey"),
            scopes: i.scopes as DeviceScope[],
            issuedAt: i.issuedAt as number,
            expiresAt: i.expiresAt as number,
          },
          sig,
          irkPub,
        );
      case "revoke-device-capability-grant":
        return verifyRevokeDeviceCapabilityGrant(
          {
            grantId: i.grantId as string,
            username: i.username as string,
            reason: i.reason as "lost" | "stolen" | "decommissioned" | "replaced",
            issuedAt: i.issuedAt as number,
          },
          sig,
          irkPub,
        );
      case "push-token-revoke":
        return verifyPushTokenRevoke(
          { tokenId: i.tokenId as string, issuedAt: i.issuedAt as number },
          sig,
          irkPub,
        );
      case "re-pair-initiate":
        return verifyRePairInitiate(
          {
            username: i.username as string,
            newIrkPub: fromHex("newIrkPub"),
            oldIrkPub: fromHex("oldIrkPub"),
            issuedAt: i.issuedAt as number,
          },
          sig,
          irkPub,
        );
      case "re-pair-object":
        return verifyRePairObject(
          {
            username: i.username as string,
            newIrkPub: fromHex("newIrkPub"),
            issuedAt: i.issuedAt as number,
          },
          sig,
          oldIrkPub,
        );
      case "admin-root-rotation":
        return verifyAdminRootRotation(
          {
            username: i.username as string,
            oldAdminRootPub: fromHex("oldAdminRootPub"),
            newAdminRootPub: fromHex("newAdminRootPub"),
            issuedAt: i.issuedAt as number,
          },
          sig,
          adminRootPub,
        );
      case "daemon-status":
      case "daemon-status-liveness":
        return verifyDaemonStatusReport(
          {
            serverDomain: i.serverDomain as string,
            certSha256: (i.certSha256 as string | null) ?? null,
            certValidUntil: (i.certValidUntil as number | null) ?? null,
            certIssuer: (i.certIssuer as string | null) ?? null,
            appsServed: i.appsServed as string[],
            nonce: i.nonce as string,
            issuedAt: i.issuedAt as number,
          },
          sig,
          stkPub,
        );
    }
    return undefined;
  };

  it("covers every vector with a typed production verifier", () => {
    const uncovered = file.vectors
      .filter((v) => v.signedBy !== "none")
      .filter((v) => typedVerify(v) === undefined)
      .map((v) => v.name);
    // If this fails, a new signed vector was added without a typed verifier here.
    expect(uncovered).toEqual([]);
  });

  for (const v of file.vectors) {
    if (v.signedBy === "none") {
      it(`vector "${v.name}" canonical-bytes recorded`, () => {
        expect(v.canonicalHex.length).toBeGreaterThan(0);
        expect(v.signatureHex).toBe("");
      });
      continue;
    }

    it(`vector "${v.name}" (signed by ${v.signedBy}) verifies via production encoder`, () => {
      expect(typedVerify(v)).toBe(true);
    });

    it(`vector "${v.name}" — recorded canonicalHex is exactly the signed bytes`, () => {
      // The recorded signature was produced over canonicalHex; verifying it
      // against those exact bytes ties the bytes the CLIENTS pin to the signed
      // payload. (typedVerify ties THOSE bytes to the production encoder.)
      const ok = ed.verify(hexToBytes(v.signatureHex), hexToBytes(v.canonicalHex), pubFor(v.signedBy));
      expect(ok).toBe(true);
    });
  }
});

// tunnel-hello's wire input uses the legacy field name `subdomains`; map it to
// the production `controlledDomains` shape for verifyTunnelHello.
function verifyTunnelHelloLocal(
  i: Record<string, unknown>,
  sig: Uint8Array,
  bakPub: Uint8Array,
): boolean {
  const fromHex = (h: string) => {
    const out = new Uint8Array(h.length / 2);
    for (let k = 0; k < out.length; k++) out[k] = parseInt(h.slice(k * 2, k * 2 + 2), 16);
    return out;
  };
  return verifyTunnelHello(
    {
      serverId: i.serverId as string,
      controlledDomains: i.subdomains as string[],
      nonce: fromHex(i.nonce as string),
      issuedAt: i.issuedAt as number,
    },
    sig,
    bakPub,
  );
}
