-- App → Service vocabulary cutover, prod-D1 fixup.
--
-- This is the live D1 patch for the App → Service rename that already
-- shipped in the migration source-of-truth files (0006, 0015, 0019,
-- 0020, 0022 — edited in-place pre-launch). Most of the renamed tables
-- haven't reached production D1 yet, so they are simply recreated from
-- their (already-renamed) CREATEs on cold-start.
--
-- The ONE table that DID make it to production is
-- `custom_domain_orders`, whose `app_id` column is renamed here to
-- `service_id`. SQLite supports `ALTER TABLE ... RENAME COLUMN` since
-- 3.25, which D1 inherits.

-- Custom domain orders: app_id → service_id. This is now a NO-OP.
--
-- The historical rename (`ALTER TABLE custom_domain_orders RENAME COLUMN
-- app_id TO service_id;`) already ran on production D1 and is tracked by NAME in
-- d1_migrations, so it never re-runs there. On any FRESH DB, migration 0022
-- already creates `custom_domain_orders` with `service_id`, so the rename is
-- redundant — and, worse, NOT replayable: it hits "no such column app_id", and
-- `wrangler d1 migrations apply` (which has no error-eliding wrapper) then aborts
-- the WHOLE apply, blocking every later migration (0027 demo_users,
-- 0038 provision_status, … through HEAD). SQLite has no conditional
-- `RENAME COLUMN`, so the only forward-only, replay-safe form is a no-op:
-- production is unaffected (already applied, tracked by name); fresh dev / gym /
-- region DBs now migrate cleanly to HEAD. (Surfaced by standing up the gym D1.)
SELECT 1;
